### ISSUE TITLE
PRESC 52-00 - Secteurs d'équipements logistiques  |  INFO 07 développement prioritaire d'économie d'énergie

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#1]
Prescription "_Infrastructures et équipements logistiques à préserver ou à développer en zones U et AU_", introduite par la version 2017d du standard.

**Comment by cartgab** [comment]
Je n'ai pas compris comment ce nouveau code a été défini et par qui.
Je ne sais pas ce qui est mis dedans? Auriez-vous un exemple d'application?

**Comment by GT-CNIG-DDU** [comment]
@cartgab c'est le GT CNIG DDU qui définit la codification, en fonction des évolutions du code de l'urbanisme.
Standard p32 : 52-00 : Infrastructures et équipements logistiques à préserver ou à développer en zones U et AU ([L151-16- 2](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000039783805/))

**Comment by cartgab** [comment]
Merci pour ces informations du standard.
Je connais le standard, je voulais avoir des exemples d’application ?

Edit : suppression informations personnelles.

**Comment by GT-CNIG-DDU** [comment]
@cartgab : merci de ne pas copier les mails ici, sinon... nous échangerions plutôt par mail 😉
La réponse est dans le code de l'urba  ([L151-16- 2](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000039783805/)) comme précisé dans le standard et ci-dessus. 
_Le règlement peut (...) également délimiter, dans les zones urbaines ou à urbaniser, des secteurs dans lesquels la préservation ou le développement d'infrastructures et d'équipements logistiques est nécessaire et définir, le cas échéant, la nature de ces équipements ainsi que les prescriptions permettant d'assurer cet objectif._
Des applications concrètes ? Si me souviens bien : les giga-zones de maintenance logistique, pour Amazon par exemple.

**Comment by JenniferIGN** [comment]
@GT-CNIG-DDU Pour ce code quels sont les types de géométries sur lesquels il s'applique (ponctuel, linéaire, surfacique) ?
Pour l'implémenter dans le GPU, on se demandait quand la symbo de ce code sera définie ? Sachant qu'en attendant on peut toujours mettre une symbolisation par défaut ;)

**Comment by GT-CNIG-DDU** [comment]
@JenniferIGN : contrairement aux premières versions (v2013 v2014) le standard PLU ne caractérise plus les prescriptions et informations par des types de géométries (car cela devenait trop compliqué à gérer, surtout lorsque le validateur respectait à la lettre le standard et que l'utilisateur voulait placer son petit ponctuel qui n'avait pas été prévu...)

Pour revenir au sujet : la PRESC 52-00 est de nature surfacique.

La définition de la symbolisation... nous appartient, nous SG5

Je propose un contour épais orange avec un poncif AMZN à l'intérieur alternant avec un sourire comme ça : 
![2021-04-02_082330](https://user-images.githubusercontent.com/79853274/113387525-c6815000-938c-11eb-973d-c38fe56612a5.jpg)
Naaannnn j'plaisante bien sûr !
(p...naise, j'arrive plus à être sérieux 2mn 🤪 il va falloir que je prenne des vacances déconfinées moi...🏖)

**Comment by JenniferIGN** [comment]
@GT-CNIG-DDU D'accord merci ! On en discute lors de la prochaine réunion du sous-groupe du coup ? (Amazon commence à te monter à la tête haha, on a tous bien besoin de ces vacances ^^)

**Comment by alhyss** [comment]
Une proposition pour cette prescription, puisque personne n'en a encore fait. Désolé, ce sera un peu court pour réagir avant la réunion de demain.

![psc_52_dev](https://user-images.githubusercontent.com/55992003/116859205-e3b17480-abff-11eb-99a2-258177384099.png)

Comme l'indiquait @GT-CNIG-DDU il s'agit a priori plutôt d'une prescription surfacique - le code de l'urbanisme ([L151-16](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000039783805/) §2) parle de "secteurs". J'ai tout de même fait une version linéaire et une version ponctuelle, au cas où.

Il n'y a pas de sens particulier derrière le symbole (hormis peut-être une vague référence à la notion de "chaîne logistique"), j'ai surtout cherché à faire quelque chose qui soit aussi distinct que possible de tous les symboles que nous avons déjà.

Je ne savais pas non plus quoi prendre pour la couleur. S'il y a une logique claire avec les symboles existants, je ne la vois pas vraiment. Le code *22 Diversité commerciale à protéger ou à développer*, qui se réfère au même article du code de l'urbanisme que le 52, utilise un gris clair. Je suis également partie sur un ton neutre, un genre de brun-gris. Le brun - avec une teinte bien plus foncée - a notamment été utilisé pour les prescriptions *27 Secteur d'aménagement numérique* et *47 Desserte pour les réseaux*, ce n'est pas complètement absurde.

Il fallait quoi qu'il en soit une teinte assez claire, car le motif surfacique est assez dense.

Pour le surfacique, trame avec des cercles entremêlés :

```
Motif de points
• distance horizontale : 10 pt
• distance verticale : 10 pt

    Symbole simple
    • couleur de remplissage (RVB) : transparent
    • couleur de trait (RVB) : 166,155,132
    • largeur de trait : 0.5 pt
    • nom du symbole : circle
    • style de trait : ligne continue
    • taille : 20 pt

Ligne simple
• couleur (RVB) : 166,155,132
• largeur de trait : 0.5 pt
• style de trait : ligne continue
```

Linéaire avec une alternance tiret/motif composé de deux cercles entremêlés. Il aurait été possible de faire un genre de chaîne (juste des cercles sans tiret), mais je trouvais le résultat beaucoup trop lourd par rapport aux autre symboles linéaires.

```
Ligne de symboles
• décalage le long de la ligne : 15 pt
• intervalle : 18 pt

    Symbole simple
    • couleur de remplissage (RVB) : transparent
    • couleur de trait (RVB) : 166,155,132
    • largeur de trait : 0.8 pt
    • nom du symbole : circle
    • style de trait : ligne continue
    • taille : 6 pt

Ligne de symboles
• décalage le long de la ligne : 12 pt
• intervalle : 18 pt

    Symbole simple
    • couleur de remplissage (RVB) : transparent
    • couleur de trait (RVB) : 166,155,132
    • largeur de trait : 0.8 pt
    • nom du symbole : circle
    • style de trait : ligne continue
    • taille : 6 pt

Ligne simple
• couleur (RVB) : 166,155,132
• largeur de trait : 0.8 pt
• modèle de tiret personnalisé (tiret ; espace) : 9;9 pt
```

Ponctuel composé de trois cercles entremêlés.

```
Symbole simple
• couleur de remplissage (RVB) : transparent
• couleur de trait (RVB) : 166,155,132
• décalage (en x, en y) : 0,-1.5 pt
• largeur de trait : 0.8 pt
• nom du symbole : circle
• style de trait : ligne continue
• taille : 6 pt

Symbole simple
• couleur de remplissage (RVB) : transparent
• couleur de trait (RVB) : 166,155,132
• décalage (en x, en y) : -1.5,1.5 pt
• largeur de trait : 0.8 pt
• nom du symbole : circle
• style de trait : ligne continue
• taille : 6 pt

Symbole simple
• couleur de remplissage (RVB) : transparent
• couleur de trait (RVB) : 166,155,132
• décalage (en x, en y) : 1.5,1.5 pt
• largeur de trait : 0.8 pt
• nom du symbole : circle
• style de trait : ligne continue
• taille : 6 pt
```

**Comment by alhyss** [comment]
Je mets une étiquette "à valider SG5", parce qu'il me semble important d'aborder le sujet de cette prescription demain (c'est problématique de ne toujours pas avoir de symbole, me semble-t-il), quitte à ce que ce soit pour dire que cette proposition ne convient pas et qu'il faudra trouver autre chose.

**Comment by GT-CNIG-DDU** [comment]
Des symboles issus de la police Webdings (disposés en poncifs, comme l'avion pour les PEB INFO 27-00) peuvent être intéressants aussi si l'on souhaite réserver le symbole proposé par @alhyss à des alternatives aux hachures sur des thèmes d'urbanisme plus abstraits. A titre d'exemples : 
![2021-05-03_150349](https://user-images.githubusercontent.com/79853274/116879757-567f1780-ac21-11eb-81e5-5f9db55545b8.jpg)
![2021-05-03_150400](https://user-images.githubusercontent.com/79853274/116879901-90e8b480-ac21-11eb-8ae5-0abc287cb825.jpg)
![2021-05-03_150516](https://user-images.githubusercontent.com/79853274/116879919-9940ef80-ac21-11eb-9020-ee6c7a358441.jpg)

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 acte la création d'un symbole basé sur un poncif, avec une teinte brun vif. La seconde proposition ci-avant est privilégiée, mais ceci impliquerait de changer le poncif utilisé pour le code INFO 07._

**Comment by alhyss** [comment]
@cartgab @JenniferIGN Est-ce qu'avec vos outils de cartographie respectifs vous seriez en mesure d'implémenter ce symbole :

```
Motif de points
• distance horizontale : 25 pt
• distance verticale : 25 pt

    Symbole de police
    • caractère(s) : unicode 57816
    • couleur de remplissage (RVB) : 172,87,13
    • famille de police : Arial
    • taille : 8 pt

Ligne simple
• couleur (RVB) : 172,87,13
• largeur de trait : 0.8 pt
• style de trait : ligne continue
```

Résultat attendu :
![psc_52_00_arial](https://user-images.githubusercontent.com/55992003/117036285-8e5f8b00-ad05-11eb-84b0-e38babd87539.png)


Concrètement, c'est le symbole de police qui m'intéresse. Je n'avais jamais remarqué jusque-là qu'Arial incluait des pictogrammes. Le thème général - les outils numériques - limite les réutilisations potentielles pour nous, mais ça resterait une source prometteuse... sous réserve que les caractères soient réutilisables.

QGIS permet de s'en servir - c'est grâce à ça que j'ai découvert leur existence - ainsi qu'Inskape, par contre LibreOffice ne paraît pas les reconnaître, d'où mon interrogation.

Le pictogramme ci-avant pourrait être une bonne alternative pour le code PSC 52, qui nous permettrait de conserver le symbole actuel pour le code INFO 07. Sinon, si on reste sur l'idée (évoquée à la réunion SG5 de ce matin) de basculer le symbole de l'INFO 07 sur la PSC 52 et d'utiliser un soleil pour pour l'INFO 07, alors le caractère Arial 57988 représente un soleil plutôt différent de celui de la PSC 25 qui  pourrait nous servir.

![arial_soleil](https://user-images.githubusercontent.com/55992003/117039301-e9df4800-ad08-11eb-9093-0c0dd349f02e.png)

![info_07_arial](https://user-images.githubusercontent.com/55992003/117039259-ddf38600-ad08-11eb-901f-5c7da71531bc.png)

**Comment by GT-CNIG-DDU** [comment]
LibreOffice en propose un certain nombre : insertion / caractères spéciaux, et naviguer ensuite dans les différents sous-ensembles.
Par contre je n'ai pas repéré les quatre flèches. Comment convertis-tu de l'unicode en décimal ou héxadécimal ? (et réciproquement)
Pour PSC 52 restons sur ce que l'on a décidé hier (bascule du symbole à double flèche de INFO 07)

**Comment by cartgab** [comment]
Je suis perdue... je ne trouve pas dans la librairie des caractères d'Arial ni l'unicode 57816 ni 57988. 
Est-ce vraiment cette librairie qui est utilisée

**Comment by alhyss** [comment]
@cartgab Avec quel outil visualises-tu les caractères ?

@GT-CNIG-DDU 57816 est la représentation unicode décimale.

Mais ce groupe de caractères codés dans les 57k n'apparaît pas du tout avec LibreOffice - en tout cas pour moi. Dans _Insertion > Caractères spéciaux_, il passe de 43877 à 62209 comme s'il n'y avait rien entre (et il dit que ça n'existe pas quand on saisit le code, d'où ta question, j'imagine). Idem si j'utilise l'utilitaire de recherche de caractère de Windows.

Par contre, je les vois dans QGIS (et j'ai accessoirement pu les utiliser aussi dans Inkscape), donc je me demande si les autres applications de cartographie (Geoserver inclus) ne les prendraient pas aussi en charge. Ce serait une option intéressante en complément des caractères Webdings et Wingdings, dont nous avons déjà largement fait le tour.

**Comment by GT-CNIG-DDU** [comment]
@alhyss : ok merci, comme toi je l'ai dans QGIS mais pas dans LibreOffice.

**Comment by cartgab** [comment]
En fait, je ne l'ai ni dans libreOffice, ni dans ArcGIS, ni dans QGIS .. Dans QGIS, je passe de 57508 à 57856 suivi de rien jusqu'à 61184

**Comment by alhyss** [comment]
@cartgab @GT-CNIG-DDU Ok. Bizarre que vous n'ayez pas la même chose dans QGIS. Tu as peut-être raison @cartgab, il se pourrait que ce ne soient pas du tout des caractères Arial et que QGIS affiche des caractères de substitution récupérés dans une autre police...

Pour le soleil, il y aurait aussi la possibilité d'utiliser le caractère 9728 (ou 2600 en hexadécimal) : ☀. Celui-là a l'intérêt d'être explicitement défini dans les tables unicode (cf. [table sur wikipédia](https://fr.wikipedia.org/wiki/Table_des_caract%C3%A8res_Unicode/U2600), c'est le premier symbole du tableau), ce qui signifie que toutes les polices qui associent un symbole à ce code (et respectent unicode) afficheront un soleil. Et c'est sans doute pour ça que GitHub le reconnaît. Celui que je mentionnais précédemment, le 57988, est dans une zone à usage privé où chaque police fait ce qu'elle veut.

Par contre, il faudrait trouver une police courante dans laquelle le symbole est implémenté et lisible. Avec Arial (ou la police de substitution utilisée par QGIS), les rayons me semblent trop fins pour être perceptibles - raison pour laquelle j'aurais préféré le 57988 : 

![info_20_9728](https://user-images.githubusercontent.com/55992003/117128557-de8a2c00-ad9d-11eb-8850-aef6cfe1c342.png)

Autre proposition, utiliser un signe infini ∞ pour l'INFO 07 (unicode décimal 8734) ? Lui a le mérite d'être implémenté dans beaucoup de polices, dont Arial. Ci-après en Arial Black, parce que c'est un peu plus lisible, me semble-t-il.

![info_07_infini](https://user-images.githubusercontent.com/55992003/117130087-da5f0e00-ad9f-11eb-90ba-6283b37f96f3.png)

```
Motif de points
• déplacement horizontal : 12 pt
• distance horizontale : 24 pt
• distance verticale : 20 pt

    Symbole de police
    • caractère(s) : unicode 8734
    • couleur de remplissage (RVB) : 132,0,168
    • famille de police : Arial Black
    • style de jointure : rond
    • taille : 14 pt

Ligne simple
• couleur (RVB) : 132,0,168
• largeur de trait : 0.8 pt
• style de trait : ligne continue
```

**Comment by cartgab** [comment]
Je trouve le symbole infini approprié pour le thème!

**Comment by alhyss** [comment]
Pour la PSC 52, avec le symbole retenu hier :
![psc_52_doubles_fleches](https://user-images.githubusercontent.com/55992003/117137783-873e8880-adaa-11eb-8976-e7842be7f83a.png)


```
Motif de points
• distance horizontale : 25 pt
• distance verticale : 25 pt

    Symbole de police
    • caractère(s) : q (unicode 113)
    • couleur de remplissage (RVB) : 172,87,13
    • famille de police : Webdings
    • taille : 11 pt

Ligne simple
• couleur (RVB) : 172,87,13
• largeur de trait : 0.8 pt
• style de trait : ligne continue
```

**Comment by JenniferIGN** [comment]
Nickel pour le 52 avec les deux flèches ! 
Que ce soit le symbole soleil ou infini pour 07 les deux me vont du moment qu'on peut les récupérer dans les polices de caractères. 
Pour les conversions décimal/hexadécimal vous pouvez utiliser cet outil : https://sebastienguillon.com/test/javascript/convertisseur.html

**Comment by GT-CNIG-DDU** [comment]
+1 pour le 52 avec les deux flèches !

Pour INFO 07 Périmètre de développement prioritaire d'économie d'énergie, au départ je voyais bien le soleil. Mais à la réflexion, ce serait bien de se le garder sous le coude pour les parcs de capteurs solaires (au fait comment sont-ils codés dans le code de l'urba ?)
Donc +1 pour l’Ouroboros car c'est le serpent qui se mord la queue et le symbole fondamental de l’alchimie spirituelle, il symbolise les deux énergies qui fondent l’univers : le conflit et l’unité.... Koi ? J'ai encore dérapé ? 😮

**Comment by cartgab** [comment]
Pour le convertisseur, il y a aussi http://www.kitsgraphiques.net/convertisseur-rvb-hexadecimal.html qui donne accès à d'autres sources html/css
