### ISSUE TITLE
Ajouts de symboles linéaires et ponctuels pour les sous-codes 05-05 et 05-06 du standard PLU

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#10]
Prescriptions 05-05 "_Emplacement réservé logement social / mixité sociale_" et 05-06 "_Servitude de localisation des voies, ouvrages publics, installations d'intérêt général et espaces verts en zone U ou AU_".

Un symbole surfacique dérivé de celui du sous-code 05-00 (rose) a été adopté pour les sous-codes 05-05 (même figuré en violet) et 05-06 (même figuré en gris), par contre aucun symbole n'est proposé pour les géométries linéaires et ponctuelles relevant de ces sous-codes.

Pas sûr que le 05-00 ait un grand intérêt, par contre les ponctuels et le 05-06 linéaires me semblent pouvoir être utiles ? **À confirmer, cependant, sinon ce n'est pas la peine d'aller plus loin.**

Dans l'absolu, il serait logique de réutiliser là encore les symboles du 05-00 :
![prescriptions_05_duplication](https://user-images.githubusercontent.com/55992003/110920523-c954cc00-831d-11eb-9a98-4f749ded72ef.png)

Problème, il y a la prescription 22 qui utilise déjà des croix grises...
![prescription_22](https://user-images.githubusercontent.com/55992003/110920614-e38eaa00-831d-11eb-87d6-2ae4b57e745f.png)

**Comment by GT-CNIG-DDU** [comment]
J'ai étudié le problème pensant au départ pouvoir jouer sur la couleur. 
Ce n'est pas souhaitables : ces symboles ne sont pas nouveaux, donc on essaye de les maintenir.
Selon moi : 
soit on conserve 05-06 et 22 tels que tu nous les présentes (la valeur du gris est différente, l'honneur est sauf ;-)
soit on adopte pour les 05 linéaires la diagonale de la surface : c'est à dire pas une succession de croix mais de carrés, en rapport plus direct avec le surfacique. Idem pour le ponctuel (un petit carré bien sûr).

**Comment by alhyss** [comment]
Comme ça ?

![prescriptions_05_carres](https://user-images.githubusercontent.com/55992003/110949064-73dee600-8342-11eb-8203-8c0a74eaf886.png)

05-05 linéaire :
```
Ligne de symboles
• intervalle : 7 pt

    Symbole simple
    • couleur de remplissage (RVB) : 255,0,0,0
    • couleur de trait (RVB) : 143,33,170
    • largeur de trait : 0.5 pt
    • nom du symbole : square
    • rotation : 45°
    • style de jointure : angle droit
    • style de trait : ligne continue
    • taille : 4 pt
```

05-05 ponctuel :
```
Symbole simple
• couleur de remplissage (RVB) : 243,166,178,0
• couleur de trait (RVB) : 143,33,170
• largeur de trait : 0.5 pt
• nom du symbole : square
• style de trait : ligne continue
• taille : 5 pt
```
(idem pour le 05-06 avec du gris)

Je trouve ça plutôt pas mal. Différent de tous les autres linéaires, en tout cas.

Quid du 05-00, par contre, est-ce qu'il reste tel quel et donc différent des 05-05/06, ou est-ce qu'il s'agirait de le modifier en conséquence ? Modifier aussi radicalement un symbole existant est délicat, mais c'est vrai qu'entre le 22 et le 43, il y a peut-être un peu trop de croix, et le fait que les intervalles ne soient jamais exactement les mêmes ne suffit pas à distinguer visuellement les symboles.

**Comment by GT-CNIG-DDU** [comment]
Ah oui, très trsè bien ! Ce n'est pas ce que j'imaginais au départ (j'imaginais un linéaire ressemblant à une échelle) mais c'est beaucoup mieux que ce que j'imaginais !
Et à mon avis : idem pour le 05-00 : le principe de cohérence à l'intérieur d'un code étant plus fort que celui de minimiser les évolutions.
Le ticket (issue / question à traiter) reste ouvert tant que non implémenté dans QGIS ;-)
+ Bon week !

**Comment by alhyss** [comment]
Dans ce cas, ça donnerait :
![prescriptions_05_carres_pour_tous](https://user-images.githubusercontent.com/55992003/110965263-4f8c0500-8354-11eb-9405-2d4781b7c8e1.png)

Ponctuel 05-00 :
```
Symbole simple
• couleur de remplissage (RVB) : transparent
• couleur de trait (RVB) : 230,0,169
• largeur de trait : 0.5 pt
• nom du symbole : square
• style de trait : ligne continue
• taille : 5 pt
```

Linéaire 05-00 :
```
Ligne de symboles
• intervalle : 7 pt

    Symbole simple
    • couleur de remplissage (RVB) : transparent
    • couleur de trait (RVB) : 230,0,169
    • largeur de trait : 0.5 pt
    • nom du symbole : square
    • rotation : 45°
    • style de jointure : angle droit
    • style de trait : ligne continue
    • taille : 4 pt
```

(j'en ai profité pour améliorer mon script de traduction pour qu'il affiche "transparent" quand le remplissage est transparent, au lieu d'une couleur quasi aléatoire avec une opacité à zéro)

@JenniferIGN Est-ce que ces symboles carrés avec une rotation de 45° seront implémentables en SLD ?

**Comment by JenniferIGN** [comment]
@alhyss oui c'est bon pour faire ça en sld :)

**Comment by alhyss** [comment]
@JenniferIGN Parfait alors !

**Comment by cartgab** [comment]
Je m'étonne que cette question n'ai pas été traitée lors de la réunion du 11 mars.
Sinon, le changement de la croix en carré entraîne, selon moi, une modification importante de la version des spécifications de M. Tanneau. J'ai cru comprendre que les évolutions proposées ne devaient pas tout remettre en cause. 
Ce changement, pour moi, ne se justifie pas. Je conserverais les croix. La proposition initiale de Leslie ma paraissait logique.

**Comment by alhyss** [comment]
@cartgab Quand tu parles de ta préférence pour la "proposition initiale", est-ce que c'est celle avec les croix pour les trois sous-codes ou celle avec des croix pour le 05-00 et des carrés pour les 05-05 et 05-06 ?

Et oui, désolée. Je voulais en parler lors de la réunion, mais j'ai oublié.

**Comment by cartgab** [comment]
Bonjour Leslie,
Oui en effet, je mentionnais le maintien du linéaire croix pour les sous-codes 05-00, 05-05 et  05-06.
Cependant pourquoi appliquer une différence de couleur pour ces seuls sous-codes ? Est-ce une demande du ministère ?

**Comment by alhyss** [comment]
@cartgab Si tu conserves les croix pour tous les symboles, que fais-tu de la similarité du 07-06 avec la prescription 22 ?

> Cependant pourquoi appliquer une différence de couleur pour ces seuls sous-codes ? Est-ce une demande du ministère ?

N'est-ce pas juste que ces sous-codes sont les seuls pour lesquels une déclinaison spécifique a été proposée (avec le 07, bien sûr, mais lui a carrément un symbole différent) ? Je pense que personne ne verrait d'inconvénient à ce que tu en suggères pour les autres si ça te semble pertinent.

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 acte la modification des symboles linéaires et ponctuels du PSC 05-00 (carrés au lieu de croix) et la création des symboles linéaires et ponctuels pour les PSC 05-05 et 05-06._

**Comment by alhyss** [comment]
Ces changements avaient déjà été mis en oeuvre - cf. pull request #22.
