### ISSUE TITLE
Demande de ressource MapFile pour MarServer

### ISSUE THREAD

**Issue by nkulpinski** [cnigfr/DDU-SG5-SYMBOLISATION#101]
Il est demandé au même titre que les ressources QGIS et ArcGISpro de mettre à disposition des fichier MapFile de bibliothèque de styles pour MapServer.
Si une âme charitable pouvait s'emparer du sujet ce serait fort apprécié
Merci

**Comment by GT-CNIG-DDU** [comment]
De mémoire le moteur graphique utilisé par le GPU est Geoserver (@JenniferIGN tu confirmes ?)

Cette demande pour Mapserver est-elle justifiée par une communauté d'utilisateurs suffisamment importante ?
Ne peut-elle être résolue par la conversion de bibliothèques de symboles que nous produisons, issues de QGIS ou ArcGIS ou Geoserver ?

Je pose la question pour évaluer le rapport coût / bénéfice pour le SG5, déjà bien occupé par la création et la maintenance des bibliothèques de symboles...

**Comment by nkulpinski** [comment]
J'ai reçu une demande par mail d'Antoine Moriceau et je soulève donc la question ;)

**Comment by GT-CNIG-DDU** [comment]
Ok. je propose que le SG5 suggère à @AntoineMoriceau d'évaluer les capacités de Mapserver à intégrer les bibliothèques de symbolisations en QML, SLD, ou ArcGIS, etc. produites et entretenues par le SG5

En effet, le sous-groupe ne serait, de mon point de vue, pas en capacité d'entretenir de synchroniser de nouvelles bibliothèques destinées à d'autres moteurs graphiques.

@AntoineMoriceau si tu nous écoutes... ;-)

**Comment by AntoineMoriceau** [comment]
Bonjour à tous. Merci Nicolas d'avoir relayé ma demande. Nous allons effectivement essayer de convertir un fichier QML en mapfile. Nous avons quelques pistes mais c'est peu probable que ce possible correctement et automatiquement. Nous allons réfléchir à d'autres stratégies pour parvenir à nos fins (probablement utiliser un autre serveur carto comme QGIS Server qui utilisera les ressources QML fournies). Je comprends en tout cas le positionnement du SG5.

**Comment by JenniferIGN** [comment]
Je confirme que le GPU utilise bien Geoserver, avec des symboles en sld
