### ISSUE TITLE
Sur-dimensionnement des symboles PSMV ?

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#11]
_... ou sous-dimensionnement des symboles PLU ?_

En lisant les préconisations de symbologie PSMV, j'ai été frappée par la différence avec les préconisations PLU : tout y est nettement plus gros.

Côté PLU, les épaisseurs de trait sont généralement à 0.5pt, parfois à 1pt quand la ligne est importante pour le motif, avec de rares exceptions à 2pt et **absolument jamais au-delà**. Côté PSMV, tout paraît avoir été augmenté. L'épaisseur est de 1pt là où elle aurait été de 0.5pt côté PLU, de 2pt au lieu de 1pt, et de 3pt au lieu de 2pt.

En outre, les ponctuels PSMV sont énormes à côté de ceux des préconisations PLU.

Le pire est la prescription 40-50 (taille 70, rien que ça), à comparer avec le plus gros symbole ponctuel des préconisations PLU :
![40_50_taille_70](https://user-images.githubusercontent.com/55992003/111518848-c3fce480-8756-11eb-950c-017125da8eec.png)

Autre exemple, les ronds verts de la prescription 07-60 PSMV (taille 22) et de la prescription 01-01 PLU (taille 7) :
![07_60_taille_22](https://user-images.githubusercontent.com/55992003/111519402-5604ed00-8757-11eb-95fc-0a807e6961b7.png)

Les symboles présentés dans l'[arrêté définissant la légende nationale](https://www.legifrance.gouv.fr/download/pdf?id=yqIzofjb3_1qq9uXOxmBuG5X-5d7dJHwKZsEdIOVbh8=) étaient effectivement de grande taille, mais il n'y avait pas de cotes explicites. Il aurait été admissible de réduire leur taille dans les préconisations pour éviter les problèmes superpositions (et ne pas rendre les symboles PLU invisibles à côté des symboles spécifiques PSMV).

Pour ce qui est des épaisseurs de trait, Stéphanie a déjà indiqué qu'elle trouvait les lignes des symboles PLU trop fines pour être visibles et même certains moteurs de rendu ont du mal à gérer des lignes à 0.5pt (comme QGIS avec les tirets...). Si on voulait mettre en cohérence les préconisations PLU/PSMV, on pourrait donc aussi envisager d'augmenter les épaisseurs côté PLU. Ou chercher un juste milieu en passant par exemple à 0.8pt le 0.5pt PLU/1pt PSMV, à 1.5pt le 1pt PLU/2pt PSMV et à 2.5pt le 2pt PLU/3pt PSMV ?

Bref :
- voulons-nous mettre en cohérence les tailles des préconisations PLU et PSMV ?
- si oui, en augmentant côté PLU, en diminuant côté PSMV ou les deux ?

**Comment by cartgab** [comment]
A noter que le point de vue 40-50 (arc rouge) est difficilement reproduisible. Il faudrait le simplifier et le faire apparaître dans le standard PLU avec le code 07-02 ou nouveau code ?

**Comment by GT-CNIG-DDU** [comment]
C'est effectivement une bonne chose de mettre en cohérence les spécifications PLU et PSMV.
A échelle identique, il ne me choquerait pas que les symbolisations PSMV soient légèrement plus marquées que celle du PLU, surtout celles propres au PSMV car le fond de plan du PSMV est a priori plus chargé que celui du PLU.
La légende nationale PSMV peut être légèrement ajustée pour ce qui concerne les tailles de symboles (puisque non spécifiée dans l'arrêté du 10/10/2018), ce qui compte est de garder l'esprit de cette légende.

- Vous voyez le PSMV PRESC 40-50 comme un ponctuel orienté ? Moi je le voyais comme deux linéaires sécants, supposant que l'angle n'étant pas nécessairement constant... (@Laetitia-aga pour ton expertise à ce sujet).

**Comment by Laetitia-aga** [comment]
Concernant la prescription 40-50. Pour le moment j'ai utilisé un ponctuel non orienté car je ne sais pas comment procédé pour orienter un ponctuel sur QGIS :). Si nous décidons d'orienter ce symbole, je suis preneuse de savoir comment faire. 

Pour la description de la symbologie voici ce que j'ai utilisé **(ATTENTION, je travaille en unité de carte et non en point)** 
![image](https://user-images.githubusercontent.com/80510168/115352739-ff585c00-a1b7-11eb-82d8-f59f9218c2c9.png)

Symbole de police
>> Couleur : 255 / 0 / 0
>> Police de caractère : Verdana - unicode 41 (parenthèse fermante)
>> Taille : 5
>> décalage x : 1,80
>> décalage y : 0,8

Symbole de police :
>> Police de caractère : Times New Roman - unicode 60 (balise ouvrante)
>> Taille : 16
>> Couleur : 255 / 0 / 0

**Comment by GT-CNIG-DDU** [comment]
Notons qu'il convient de questionner le Ministère de la Culture pour savoir si ce symbole est : ponctuel (ou bi-linéaire ??), orienté et si l'angle est variable ou constant.

**Comment by GT-CNIG-DDU** [comment]
_[hors sujet - post à supprimer ultérieurement]_
@Laetitia-aga : ouvre une issue si nécessaire pour le deuxième sujet (ta question), sinon on s'y perd...

**Comment by alhyss** [comment]
Si le 40-50 est un ponctuel orienté d'angle variable (ou juste un ponctuel orienté), alors je n'ai pas l'impression que le standard en permette une prise en charge propre. Il y aurait des solutions pour gérer ces paramètres pour un PSMV donné, soit en mobilisant le champ `TXT`, soit avec des champs optionnels, mais est-ce qu'on irait jusqu'à écrire ça dans le standard ?

En imaginant que l'angle et l'orientation soient définis dans les données (deux valeurs numériques correspondant aux angles d'azimut des deux segments, par exemple), on pourrait sans difficulté produire dans QGIS un ponctuel avec les deux lignes qui symbolisent le cône de vue. L'arc de cercle de longueur variable, par contre, ça ne paraît vraiment pas trivial... Les styles "basiques" de QGIS ne le permettent pas, il faudrait probablement utiliser un [SVG dynamique](https://docs.qgis.org/testing/en/docs/user_manual/style_library/symbol_selector.html#parametrizable-svg), ce qui est une [nouveauté de la version 3.18](https://qgis.org/en/site/forusers/visualchangelog318/index.html#feature-gui-for-dynamic-svgs)...

Si on considère que le symbole doit ou peut être dessiné à la main avec une géométrie linéaire, ça a l'avantage d'être plus simple pour nous - la spécification sera complètement triviale (ligne simple rouge d'épaisseur à préciser). Mais on reporte juste la difficulté sur ceux qui conçoivent les documents.

Dans un premier temps - en attendant la position du ministère de la culture sur la nécessité ou non d'orienter ce symbole et une éventuelle décision sur la manière de gérer ça dans le standard - on pourrait se contenter de définir :
- une spécification figée pour les géométries ponctuelles (juste plus petite que l'actuelle, je maintiens ma remarque à ce sujet) ;
- une spécification pour les géométries linéaires, pour les concepteurs de PSMV qui ont fait le choix de dessiner de véritables cônes de vue sur leurs plans.

Si ça paraît pertinent, je peux créer le SVG dynamique. On ne s'en servirait pas pour les QML, mais on peut le mettre à disposition pour ceux qui sont sur la version 3.18 de QGIS et expliquer comment s'en servir.

EDIT : coquilles.

**Comment by GT-CNIG-DDU** [comment]
Je viens de poser la question par mail au Ministère de la Culture, afin de savoir 
- si le symbole est orienté
- si le symbole est ponctuel ou bi-linéaire ou cela les importe peu
- si l'angle est constant à 30°
- si l'arc de cercle à proximité de l'intersection est important ou pas
Les réponses nous guideront vers celles à t'apporter @alhyss

**Comment by alhyss** [comment]
J'ajoute une étiquette `à valider SG5` pour que nous tranchions demain les questions d'épaisseurs de trait et de tailles relatives des symboles PSM/PLU évoquées dans le premier message. Nous en avons besoin pour avancer dans la production des QML PSMV.

La suite des discussions sur la manière de représenter le 40-50 pourrait se faire dans une autre issue.

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 acte :_
* _d'augmenter à 0.8pt les épaisseurs de 0.5pt des spécifications PLU ;_
* _d'aligner les épaisseurs de trait PSMV sur celles des PLU ;_
* _d'établir les spécifications surfaciques PSMV en suivant les dimensions apparentes de la légende nationale ;_
* _d'établir les spécifications linéaires et ponctuels PSMV avec des tailles plus petites que les dimensions apparentes de la légende nationale et plus adaptées à l'usage. Il est possible de conserver des tailles légèrement plus importantes pour les symboles PSMV que pour les symboles PLU._

**Comment by alhyss** [comment]
_L'augmentation à 0.8pt des épaisseurs de traits à 0.5pt des spécifications PLU a été mise en oeuvre par le pull request #35. Les autres décisions sont des lignes de conduite pour la suite et ne requièrent pas d'action sur l'existant. Je clos le ticket._
