### ISSUE TITLE
Modification de la transposition de la légende nationale pour la prescription PSMV 07-61

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#12]
Prescription PSMV 07-61 "_Place, cour ou autre espace libre à dominante minérale protégé (pavés, calades, etc.), à conserver, restaurer et mettre en valeur_".

Dans la [légende nationale](https://www.legifrance.gouv.fr/download/pdf?id=yqIzofjb3_1qq9uXOxmBuG5X-5d7dJHwKZsEdIOVbh8=), ce figuré présente une trame irrégulière :
![07_61_poste_legende_nationale](https://user-images.githubusercontent.com/55992003/111588647-217b4a80-87c4-11eb-9e59-3cf6abb648ab.png)

... alors que c'est un ponctuel régulier (et plus dense) qui a été utilisé dans les préconisations :
![07_61_preconisations](https://user-images.githubusercontent.com/55992003/111588915-76b75c00-87c4-11eb-8fbf-c0f74c6529f0.png)

Le résultat me semble trop différent.

Il est sans doute possible de rendre l'aspect de la trame encore plus semblable à la légende en ajustant les paramètres, mais je proposerais plutôt quelque chose comme ça pour les préconisations PSMV :
![07_61_qml](https://user-images.githubusercontent.com/55992003/111590854-f21a0d00-87c6-11eb-8de2-1f9c04a1d844.png)

```
Motif de points
• déplacement horizontal : 1.5 pt
• déplacement vertical : 3 pt
• distance horizontale : 4 pt
• distance verticale : 4 pt

    Symbole de police
    • caractère(s) : l (unicode 108)
    • couleur de remplissage (RVB) : 100,50,0
    • famille de police : Wingdings
    • taille : 1 pt

Ligne simple
• couleur (RVB) : 100,50,0
• largeur de trait : 1 pt
• style de trait : ligne continue
```

**Comment by GT-CNIG-DDU** [comment]
J'adhère entièrement à cette proposition de symbolisation du PSMV PRESC 07-61 👍

**Comment by Laetitia-aga** [comment]
J'ai modifié un peu les styles pour un usage "papier" et ce afin de pouvoir lire la totalité du plan sous format A0. Pour une meilleure lisibilité des natures de prescription, j'ai opté pour le code 07-61 pour des points réguliers. 

![image](https://user-images.githubusercontent.com/80510168/115352830-17c87680-a1b8-11eb-864b-a7714b41f19c.png)


Encore une fois, nous travaillons pour un usage "fixe" des plans et non pour une version numérique, mes remarques sont peut-être donc à côté de la plaque [...]

**Comment by GT-CNIG-DDU** [comment]
En relation avec #13 et #11 : dans ce cas précis le respect de la légende nationale PSMV militerait nettement pour la symbolisation avec un poncif irrégulier, ce qui permet également de se différencier du poncif à "gros points" utilisé par 01-01 et 07-57.
La prise en compte de l'usage papier grand format est pertinente mais en quoi la régularité du poncif est-elle préférable à l'irrégularité pour ce poste de légende et cet usage ?

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 valide la proposition (trame irrégulière)._
