### ISSUE TITLE
Modification de la transposition de la légende nationale pour la prescription PSMV 07-57

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#13]
Prescription PSMV 07-57 "_Parc ou jardin de pleine terre protégé, à conserver, restaurer et mettre en valeur_".

Figuré de la légende nationale :
![07_57_legende_nationale](https://user-images.githubusercontent.com/55992003/111786357-fecd5c80-88bd-11eb-95f5-b11e00de58b6.png)

Visuel des préconisations de symbologie PSMV :
![07_57_visuel_specifications](https://user-images.githubusercontent.com/55992003/111786480-26242980-88be-11eb-91de-1086bedcf393.png)

Application des spécifications des préconisations de symbologie PSMV (en supposant que le symbole utilisé est le caractère Webdings 61, car ce n'est pas spécifié) :
![07_57_webdings_61](https://user-images.githubusercontent.com/55992003/111796661-aea7c780-88c8-11eb-9569-bf2eadbd9255.png)

Les spécifications donnent des points bien plus gros et espacés que dans la légende nationale. Ne faudrait-il pas les revoir pour avoir un symbole qui corresponde véritablement à la légende ?

_EDIT 2021.03.19 : le figuré des préconisations a visiblement été fait avec un symbole de police (probablement Webding 61) et non un symbole simple circle comme je le supposais au départ. De cette façon, le visuel du tableau et la description littérale sont cohérents. Modification du descriptif en conséquence._

**Comment by cartgab** [comment]
Bonjour,
Ce serait peut-être l'occasion de faire un compromis entre le standard PSMV et PLU en appliquant le symbole du standard du PLU avec une différence : le cercle ne serait pas blanc mais sans couleur.

**Comment by alhyss** [comment]
@cartgab Désolée, je ne comprends pas ce que tu veux dire.

Les symboles PLU pour la prescription 07, ce sont les étoiles :

![psc_07_plu](https://user-images.githubusercontent.com/55992003/112548057-ed9fb680-8dbb-11eb-9455-1f5990c81cc2.png)

**Comment by Laetitia-aga** [comment]
Je pense que l'on ne peut pas envisager de changer la symbologie du 07-57. En effet certains symbole sont fixées par l'arrêtés du 10 octobre 2018 (https://www.legifrance.gouv.fr/download/pdf?id=yqIzofjb3_1qq9uXOxmBuMiBBOvFBquP8SLVDhQ4mrg=).

**Comment by GT-CNIG-DDU** [comment]
Cf ma remarque dans issue #11 : _"La légende nationale PSMV peut être légèrement ajustée pour ce qui concerne les tailles de symboles (puisque non spécifiée dans l'arrêté du 10/10/2018), ce qui compte est de garder l'esprit de cette légende."_

**Comment by alhyss** [comment]
Figuré proposé dans les [spécifications publiées sur la branche bêta](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#prescription-07-57) :

![PSC-07-57](https://user-images.githubusercontent.com/55992003/130452051-c11f8960-ef1c-418e-8201-b5351a3d4fb7.png)

```
Motif de points
• distance horizontale : 10 pt
• distance verticale : 10 pt

    Symbole simple
    • couleur de remplissage (RVB) : 90,140,40
    • nom du symbole : circle
    • taille : 5 pt

Ligne simple
• couleur (RVB) : 90,140,40
• largeur de trait : 0.8 pt
• style de trait : ligne continue
```

Les points sont légèrement plus espacés que dans la légende nationale. Il serait tout à fait possible d'y remédier (dites-moi !), mais je trouvais le rendu un peu plus satisfaisant de cette façon pour le symbole [PSC 01-00](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#prescription-01-01) , qui est son alter ego avec des lignes (ou des carrés, en pratique).

![PSC-01-00](https://user-images.githubusercontent.com/55992003/130452878-2beae56f-3da3-4aa0-9239-b0e98167179d.png)

**Comment by alhyss** [comment]
_Le SG5 du 2021.09.07 valide la dernière proposition._
