### ISSUE TITLE
Plugin QGIS Resource Sharing - pour utiliser des ressources QML dans un projet QGIS

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [cnigfr/DDU-SG5-SYMBOLISATION#15]
Je mets ceci ici pour mémoire, et test éventuel si vous le jugez pertinent.

Le plugin QGIS Resource Sharing permet de partager tout type de ressources pour QGis : des bibliothèques de symboles, de styles, des images et des scripts. Ces éléments peuvent être entreposés à distance (pour l’instant le plugin supporte **Github** et Bitbucket comme dépôts publics), le système de fichiers local, ou un serveur http avec des collections zippées.

https://plugins.qgis.org/plugins/qgis_resource_sharing/

https://www.sigterritoires.fr/index.php/partagez-vos-ressourcessymbolesimagesscripts-pour-qgis-avec-le-nouveau-plugin-resource-sharing/

**Comment by alhyss** [comment]
Dans le même esprit, la publication de la version 3.18 de QGIS s'est accompagnée de l'ouverture de dépôts en ligne pour, notamment, partager les [styles](https://plugins.qgis.org/styles/) et les [projets](https://plugins.qgis.org/geopackages/), dans l'esprit de ce qui se faisait déjà pour les plugins.

En conséquence, le gestionnaire de style permet désormais d'aller récupérer des styles sur ce dépôt en ligne (cf. explications dans la [note de version de la 3.18](https://qgis.org/fr/site/forusers/visualchangelog318/index.html#feature-open-the-style-gallery-from-the-style-manager)).
