### ISSUE TITLE
Changement de symbole pour INFO 02-00 ZAC 

### ISSUE THREAD

**Issue by cartgab** [cnigfr/DDU-SG5-SYMBOLISATION#16]
Suite à la dernière réunion, le proposition ne semble plus d'actualité.
Toutefois, j'insiste, quand cette information s'affiche, elle masque toutes les autres.
La proposition, si tout de même traitée, est
![image](https://user-images.githubusercontent.com/80674754/112477581-73e3da80-8d73-11eb-91b8-917b06d1f9ca.png)
Symbole de ligne de remplissage :
>> Angle : 45  
>> Séparation : 12
>> Couleur RVB : 0/255/255
>> Contour symbole de ligne cartographique:
>> Couleur RVB : 0/255/255
>> Modèle 5 grades sur 10 et intervalle 1
>> Epaisseur : 1,5
La couleur bleue a été choisie car bien visible sur une zone urbaines (dans les tons bordeau/violet)
La description sera traduite en qml si validée.
Et, malgré la relecture de la page 14 du standard, je ne comprends pas le maintien (ou création) de la ZA en tant que prescription dans le code 45-00 et information 02-00. Selon moi, les ZA font toujours l'objet d'un aménagement particulier prévu dans le PLU. 
Encore une fois, cela dépasse mes compétences en termes d'urbanisme.

**Comment by alhyss** [comment]
> Toutefois, j'insiste, quand cette information s'affiche, elle masque toutes les autres.

C'est ce que j'ai du mal à comprendre, pour ce cas-là mais aussi ceux des issues #17 et #18.

Avec QGIS, tu as beaucoup de possibilités pour t'assurer que les aplats ne recouvrent pas les autres éléments :
- l'ordre des couches, pour commencer par le plus trivial, qui permet déjà de faire en sorte que les points soient au-dessus des lignes et les lignes au-dessus des polygones ;
- les *Niveaux de symboles* qui permettent d'indiquer, pour une couche donnée, l'ordre dans lequel les symboles doivent être dessinés. Je m'en suis servi pour les QML, soit dit en passant, pour faire en sorte que les aplats se retrouvent en dessous, puis les maillages denses, puis les maillages légers. C'est sans doute perfectible - j'ai fait ça vite fait et sans tester le rendu - mais la possibilité technique existe ;
- l'option *Contrôle de l'ordre de rendu des entités*, qui pourrait aussi être mise à profit pour s'assurer que certains codes ou sous-codes soient dessinés en premier pour ne pas recouvrir les autres.

Où est-ce que le problème se pose quand tu ne travailles pas avec QGIS ?

La transparence de couche à 40% sur les informations surfaciques doit pouvoir aider un peu sinon. Pas aussi efficace que de jouer sur l'ordre de rendu, mais si tu es sur de la cartographie web avec des possibilités de mise en forme limitées ça doit au moins permettre à l'utilisateur de voir qu'il y a une superposition (et il pourra interroger les couches pour comprendre de quoi il est question si ce n'est pas très facile à discerner).

Autre aspect, je suis réservée sur l'idée de multiplier les surfaciques avec des hachures et des contours pointillés. Les informations 21-00, 22-00 et 25-00 sont déjà sur ce modèle, changer la couleur et l'inclinaison des hachures ne suffit pas à faire des symboles visuellement distincts. Cette remarque vaut là encore également pour les issues #17 et #18.

![info_21_22](https://user-images.githubusercontent.com/55992003/112546301-91d42e00-8db9-11eb-908a-fabe8a297a1b.png) 

![info_25](https://user-images.githubusercontent.com/55992003/112546312-94cf1e80-8db9-11eb-822a-5d1e925586c0.png)

**Comment by GT-CNIG-DDU** [comment]
Je suis d'accord avec @alhyss sur la réserve à l'idée de multiplier les surfaciques avec des hachures et des contours pointillés, et voir  ma remarque concernant INFO 20-00 dans #18

**Comment by cartgab** [comment]
C'est bien noté pour la non multiplication des hachures (plomb, ). 
Les hachures sont intéressantes pour ne pas masquer les autres informations.
Et en générale les hachures s'appliquent sur des zones importantes.

**Comment by alhyss** [comment]
@cartgab es-tu d'accord pour fermer l'issue, dans la mesure où le SG5 du 11/03 a déjà acté de conserver la prescription *45 Zone d'aménagement concerté*, qui utilise le même symbole (sans transparence).

Accessoirement, je vais modifier le titre pour faire apparaître le code.

**Comment by cartgab** [comment]
Si cela ne dérange pas, j'aimerais vraiment en discuter avec les autres participants.
La difficulté est que sur un plan de zonage, on ne peut pas présenter la ZA car masque les informations et zonage en dessous.
D'autant que dans certains cas la couleur choisi correspond à la couleur du zonage.

**Comment by alhyss** [comment]
@cartgab Merci pour ton retour. Je l'ai mis dans les points à traiter demain.

Pour ma part, au-delà du fait qu'il est toujours préférable de minimiser les changements (surtout aussi drastiques) sur les symboles existants et du fait que le projet de gestion de la symbolisation pourrait aussi permettre de proposer des alternatives aux aplats sans avoir à bouleverser les préconisations de symbolisation, je ne serais pas absolument choquée à l'idée de remplacer ce symbole et plus généralement tous ceux qui utilisent des aplats (sauf l'information 98).

Mais pas avec le symbole que tu proposes. Si nous renonçons aux aplats, il me semble que nous devons inventer des trames surfaciques aisément discernables pour chaque symbole concerné.

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 acte de conserver le symbole actuel à ce stade._
