### ISSUE TITLE
Changement de symbole pour INFO 03-00 (ENS) , 04-00 (DPU), 04-00 (DPU renforcé) et 33-00 (DP commercial)

### ISSUE THREAD

**Issue by cartgab** [cnigfr/DDU-SG5-SYMBOLISATION#17]
Suite à la dernière réunion, les propositions de remplacer l’aplat plein par ligne ne semblent plus d'actualité.
Cependant à l'échelle où cette information s'affiche, elle masque toutes les autres.
De plus, le triangle extérieur est peu pratique quand on applique un calque pour mettre un fond blanc autour de la commune (pour masquer les informations des communes voisines). Pour le DP ENS, le symbole devient un aplat vert à contour simple.

Donc si la question est posée, voici les propositions.
elles seront traduites en qml si nécessaire.

Proposition pour DPU
![image](https://user-images.githubusercontent.com/80674754/112476965-bce75f00-8d72-11eb-9fe8-d4c112077a11.png)
Symbole de ligne de remplissage :
>> Angle : 90  
>> Séparation : 12
>> Couleur RVB : 255/101/101
>> Largeur : 0.5
>> Contour symbole de ligne cartographique:
>> Modèle 5 grades sur 10 et intervalle 1
>> Couleur RVB : 255/101/101
>> Epaisseur : 1,5

Proposition pour DPU renforcé 
![image](https://user-images.githubusercontent.com/80674754/112477081-e4d6c280-8d72-11eb-93ef-56ecc2205394.png)
Symbole de ligne de remplissage :
>> Angle : 90  
>> Séparation : 12
>> Epaisseur : 3
>> Décalage : 0
>> Couleur RVB : 255/101/101
>> Contour symbole de ligne cartographique:
>> Contour  RVB: 255/101/101
>> Modèle 5 grade

Proposition pour DP ENS
![image](https://user-images.githubusercontent.com/80674754/112476813-988b8280-8d72-11eb-8fe5-bec6302eaebc.png)
Symbole de ligne de remplissage :
>> Angle : 330 / 60 
>> Séparation : 24
>> Couleur RVB : 134/213/47
>> RVB contour : 134/213/47 
>> Epaisseur : 0,5
Symbole de ligne de remplissage :
>> Angle :30  
>> Séparation : 24
>> Couleur RVB : 134/213/47
>> RVB contour : 134/213/47 
>> Epaisseur : 0,5
Contour épaisseur 0.5

**Comment by alhyss** [comment]
> De plus, le triangle extérieur est peu pratique quand on applique un calque pour mettre un fond blanc autour de la commune (pour masquer les informations des communes voisines). Pour le DP ENS, le symbole devient un aplat vert à contour simple.

@cartgab Je ne sais pas avec quel outil tu es confrontée à cette difficulté, mais il existe dans QGIS des possibilités pour masquer les éléments non pertinents tout en respectant les symboles des éléments affichés (notamment avec des filtres jouant sur les variables d'atlas). Je serais réticente à écarter les triangles pointant vers l'extérieur pour cette seule raison. Posent-ils d'autres problèmes ?

Indépendamment de l'intérêt qu'il y aurait à changer les symboles, j'aurais le même genre de réserve ici que dans l'issue #16 : les propositions actuelles me semblent un peu trop proches de symboles existants.

En matière de rayures verticales, nous avons déjà la prescription 18 (OAP).
![PSC-18-00](https://user-images.githubusercontent.com/55992003/116905414-3c543200-ac3f-11eb-9821-fa65e441034f.png)

En matière d'association contour pointillé + hachures (certes pas tout à fait verticales), nous avons déjà les informations 21, 22, 25.
![INFO-21-00](https://user-images.githubusercontent.com/55992003/116905470-4f670200-ac3f-11eb-809d-78f15de8ee3b.png) ![INFO-22-00](https://user-images.githubusercontent.com/55992003/116905481-542bb600-ac3f-11eb-97be-8a01dead1381.png) ![INFO-25-00](https://user-images.githubusercontent.com/55992003/116905487-568e1000-ac3f-11eb-81f2-909e50e7baa9.png)

Nous n'avions pas encore de carroyage à base de losanges, mais nous avions déjà plusieurs motifs de carrés larges avec les prescriptions 32 et 43 :
![PSC-32-00](https://user-images.githubusercontent.com/55992003/116905666-93f29d80-ac3f-11eb-8fcc-e7738da5db81.png) ![PSC-43-00](https://user-images.githubusercontent.com/55992003/116905686-98b75180-ac3f-11eb-822b-bfdf32f4ca42.png)

Tout ceci étant dit, je n'aime pas beaucoup le symbole 04-01 actuel. Les poncifs "DPU" sont très espacés, j'ai peur que dans la plupart des cas le symbole apparaisse identique à celui de l'information 04-00 (dont il ne se distingue que par le poncif en question) :
![INFO-04-01](https://user-images.githubusercontent.com/55992003/116903837-3e1cf600-ac3d-11eb-8dbd-3d3af91ad367.png) ![INFO-04-00](https://user-images.githubusercontent.com/55992003/116903878-512fc600-ac3d-11eb-8665-bac7100f2e05.png)

**Comment by cartgab** [comment]
Les triangles extérieurs posent 2 problèmes:
-Bien que le SIG contient les 36 communes de l'agglo, il est nécessaire de publie les PLU par commune. En effet, il n'y a pas de PLUI sur le territoire.
Pour ne pas afficher les informations de la commune voisine, un masque blanc a été appliqué sur les communes voisines. par conséquent, l'ENS (triangle vert extérieur) apparaît comme un tiret vert.
- De plus, il y a une difficulté pour publier ce type de symbole depuis AGS. Il est nécessaire de créer un cache de tuiles spécifique à cette symbologie. Je la trouve trop couteuse par rapport à son intérêt.

Pour le DPU, l'inscription DPU peut masquer des informations plus essentielles au PLU que le DPU (qui s'applique à toutes les zones urbaines en général).

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 acte de modifier les symboles des codes INFO 03, 04-00, 04-01 et 33 en orientant les triangles vers l'intérieur._
