### ISSUE TITLE
Changement de symbole pour INFO 20-00 (règlement de publicité)

### ISSUE THREAD

**Issue by cartgab** [cnigfr/DDU-SG5-SYMBOLISATION#18]
Suite à la dernière réunion, les propositions de remplacer l’aplat plein par ligne ou contour seul ne semble plus d'actualité.
Cependant, que penseriez-vous d'un symbole surfacique avec un seul contour à hachures intérieure. Car selon son échelle d'affichage, il masque toutes les autres informations et prescription. Cette remarque rejoint les propositions faites et abandonnées des DPU, DP ENS, DP Commercial.

![image](https://user-images.githubusercontent.com/80674754/112476444-32066480-8d72-11eb-9786-ed0c92ff24f5.png)

Symbole de remplissage simple 
>> Couleur : Aucune
Contour
Symbole ligne simple
>> Largeur 1,5
>> Couleur RVB : 255/85/0
Symbole ligne à barbules 
>> Angle 90
>> Largeur 5
>> Modèle : 1 grade sur 10 et intervalle 1
>> Décalage : -3
>> Couleur RVB : 255/85/0

Je le traduirais en QGIS si telle est la volonté.

**Comment by GT-CNIG-DDU** [comment]
@cartgab : d'accord pour revoir cette symbolisation mais cette proposition pour INFO 20-00 serait identique à INFO 21-00.
Mieux vaut différencier nettement les règlement de publicité (INFO 20-00) des projet de PPRR (INFO 21-00)

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 acte le changement de symbole. Pas de figuré adopté à ce stade._

**Comment by cartgab** [comment]
Je propose soit 
- le contour à barbules
![image](https://user-images.githubusercontent.com/80674754/117110066-e63dd680-ad85-11eb-9972-e20dbb7df5b7.png)
ou 
- le haut-parleur
![image](https://user-images.githubusercontent.com/80674754/117110922-25b8f280-ad87-11eb-91c0-5b404447e582.png)

Je ferai le qml après avis et validation du symbole.

**Comment by alhyss** [comment]
@cartgab Ta première proposition ("contour à barbules") est quasi identique au symbole de la PSC 25.
![PSC-25-00](https://user-images.githubusercontent.com/55992003/117116735-01611400-ad8f-11eb-95c5-55ae22a273c1.png)

Pour la seconde proposition... Je crois que la "publicité" dont il est question ici est purement visuelle. Cf définition à l'[article L581-3 1° du code de l'environnement](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000006834686) : "_Constitue une publicité, à l'exclusion des enseignes et des préenseignes, toute inscription, forme ou image, destinée à informer le public ou à attirer son attention, les dispositifs dont le principal objet est de recevoir lesdites inscriptions, formes ou images étant assimilées à des publicités_". Dans ce contexte, je ne suis pas sûre qu'un haut-parleur soit un pictogramme adapté.

Une suggestion supplémentaire :

![info_20_ligne_carreaux](https://user-images.githubusercontent.com/55992003/117121409-d5489180-ad94-11eb-9e68-b10c896c8acd.png)

```
Motif de points
• décalage horizontal : -3 mm
• décalage vertical : 3 mm
• déplacement horizontal : 6 mm
• distance horizontale : 12 mm
• distance verticale : 6 mm

    Symbole de police
    • caractère(s) : . (unicode 46)
    • couleur de remplissage (RVB) : 255,85,0
    • famille de police : Webdings
    • taille : 3 mm

Motif de points
• déplacement horizontal : 6 mm
• distance horizontale : 12 mm
• distance verticale : 6 mm

    Symbole de police
    • caractère(s) : . (unicode 46)
    • couleur de remplissage (RVB) : 255,85,0
    • famille de police : Webdings
    • taille : 3 mm

Ligne simple
• couleur (RVB) : 255,85,0
• largeur de trait : 0.8 pt
• style de trait : ligne continue
```

**Comment by cartgab** [comment]
Je suis d'accord pour le contour à barbules. Cependant la zone de publicité ne devrait pas se superposer avec une trame verte (code 25).
Le haut-parleur (Webdings unicode 88) me semblait ntéressant pour le "porté à connaissance".
Je ne sais pas pour le symbole carré, il me fait penser à la prescription 05 linéaire même si la couleur est différente.

**Comment by GT-CNIG-DDU** [comment]
Le symbole carré me parait dense et le poncif ressembler à une hachure.
S'agissant de secteurs où les panneaux publicitaires sont limités (ou interdits ?) un rectangle barré me semblerait évocateur
Par exemple le caractère Wingdings 61560, dans un poncif pas trop dense.
![2021-05-05_153241](https://user-images.githubusercontent.com/79853274/117149067-25385000-adb7-11eb-8059-0fbb0e50acae.jpg)
Ou de préférence Wingdings2 61523, plus léger :
![2021-05-05_153344](https://user-images.githubusercontent.com/79853274/117149198-4a2cc300-adb7-11eb-9180-ab74c1f2df41.jpg)

**Comment by alhyss** [comment]
J'ai une préférence pour le Wingdings 61560, qui fait moins case à cocher comme il n'est pas carré (et ça le distingue davantage des symboles carrés déjà utilisés ailleurs).

Tant qu'il reste de petite taille, il ne paraît pas dense :

![info_20_rectangle_croix](https://user-images.githubusercontent.com/55992003/117182454-a8b56980-add6-11eb-870d-2ca7c497857c.png)

```
Motif de points
• déplacement horizontal : 13 pt
• distance horizontale : 26 pt
• distance verticale : 26 pt

    Symbole de police
    • caractère(s) : unicode 61560
    • couleur de remplissage (RVB) : 255,85,0
    • famille de police : Wingdings
    • taille : 8 pt

Ligne simple
• couleur (RVB) : 255,85,0
• largeur de trait : 0.8 pt
• style de trait : ligne continue
```

Il n'est pas mal non plus à la vertical, soit dit en passant :

![info_20_rectangle_croix_vertical](https://user-images.githubusercontent.com/55992003/117182844-25484800-add7-11eb-8360-0e126298b7f9.png)

**Comment by GT-CNIG-DDU** [comment]
Oui, pas mal aussi en vertical. Cela rappelle les panneaux lumineux (ou pas) dans ce format, et cela fait moins "case cochée".

**Comment by cartgab** [comment]
La case cochée se rapproche des symboles avec "virgule" dans la case de l'information 51-00. Je ne suis pas certaine que sur un plan la distinction entre la croix et le point se fasse (prescription 19-00).
Je réitère ma préférence du haut-parleur pour la communication par rapport à une case cochée.

**Comment by alhyss** [comment]
Pour garder l'idée d'un panneau barré tout en le rendant moins facile à confondre avec la PSC 51 :

![info_20_rectangle_barre](https://user-images.githubusercontent.com/55992003/117256243-b99fc280-ae4a-11eb-918b-451a794eb6a3.png)

```
Motif de points
• déplacement horizontal : 15 pt
• distance horizontale : 30 pt
• distance verticale : 30 pt

    Symbole simple
    • couleur de remplissage (RVB) : transparent
    • couleur de trait (RVB) : 255,85,0
    • largeur de trait : 0.8 pt
    • nom du symbole : half_square
    • style de trait : ligne continue
    • taille : 8 pt

Motif de points
• déplacement horizontal : 15 pt
• distance horizontale : 30 pt
• distance verticale : 30 pt

    Symbole simple
    • couleur de trait (RVB) : 255,85,0
    • décalage (en x, en y) : -2,0 pt
    • largeur de trait : 0.8 pt
    • nom du symbole : cross2
    • style de trait : ligne continue
    • taille : 10 pt

Ligne simple
• couleur (RVB) : 255,85,0
• largeur de trait : 0.8 pt
• style de trait : ligne continue
```

**Comment by GT-CNIG-DDU** [comment]
Parfait ! C'est l'idée que j'avais en tête, sans avoir trouvé le bon symbole dans les polices de caractères.

**Comment by LaureVatonne** [comment]
Suite à cette issue, côté GPU, nous proposons la symbo suivante. Si vous avez des remarques par rapport au symbole proposé dans l'issue, n'hésitez pas à nous en faire part.
![image](https://user-images.githubusercontent.com/94525722/160860817-d2e2240c-a87e-4181-baf2-4392418a661c.png)

**Comment by cartgab** [comment]
c'est parfait
