### ISSUE TITLE
Modification couleur symbole INFO 14-00 (bruit)

### ISSUE THREAD

**Issue by cartgab** [cnigfr/DDU-SG5-SYMBOLISATION#19]
Il est proposé de conserver les symboles mais de changer la couleur du linéaire car non visible sur le site du GPU et sur un plan. 
La couleur proposée a le code 115/38/0 
![image](https://user-images.githubusercontent.com/80674754/112476258-008d9900-8d72-11eb-9bab-47b50e15bb8b.png)
Je traduirais en qml si validé

Pour les surfaciques, la distinction des classes de bruit devrait être traitée par le groupe DDU le 7 avril

**Comment by GT-CNIG-DDU** [comment]
@cartgab : on ne modifierait que la couleur INFO 14-00 linéaire (actuellement rose et effectivement peu visible) ou également celle du surfacique, et dans ce cas de l'intérieur et/ou du contour ?

**Comment by cartgab** [comment]
Si cette information reste en l'état, pour plus de cohérence il est vrai qu'il faudrait appliquer la même couleur pour la donnée linéaire et surfacique.

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 acte d'utiliser la même couleur pour le symbole linéaire que pour le symbole surfacique (rose plus vif) et d'augmenter d'1pt la taille des cercles._
