### ISSUE TITLE
Création d'un symbole pour la prescription 97-01 du standard PLU

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#2]
Prescription "_Périmètre couvert par un plan de secteur_", introduite par la version 2017c du standard PLU, dans le cadre de la prise en charge des pièces écrites territorialisées.

**Comment by alhyss** [comment]
Proposition pour les géométries surfaciques :
```
Ligne simple
• couleur (RVB) : 0,0,0
• largeur de trait : 2 pt
• style de trait : ligne tiret-point-point
```
![proposition_97_01](https://user-images.githubusercontent.com/55992003/110807846-b8577c80-8283-11eb-965c-dcda27a0fe08.png)

C'est proche du contour noir du 99, mais le style tiret-point-point les rend impossibles à confondre. L'information 05 utilisait déjà un contour de ce genre, mais du tiret-point au lieu de tiret-point-point, en bleu et pas noir, et avec une trame à l'intérieur... Bref, ça me semble suffisamment différent.

Il n'y a pas lieu de créer de symboles pour les géométries linéaires ou ponctuelles, me semble-t-il.

**Comment by GT-CNIG-DDU** [comment]
Oui cela me parait très bien, je pensais un peu à cela.
C'est le style de symbole employé pour les limites communales / interco / dept dans la légende PSMV.
En fait cela ressemble tout à fait à la "limite d'intercommunalité" dans la légende PSMV, mais je ne le vois pas comme un problème, plutôt une forme de cohérence.
Pour moi c'est ok.

**Comment by alhyss** [comment]
Je n'étais pas allée vérifier la légende PSMV...

Le bon côté, c'est que ce n'est pas exactement le même. La limite d'intercommunalité semble être en tiret-tiret-point-point et pas tiret-point-point (je dis "semble" parce que le motif n'est pas répété, donc on ne peut pas vraiment en être sûr...). Et la taille relative des points par rapport aux tirets est plus petite.

![psmv_limite_intercommunalite](https://user-images.githubusercontent.com/55992003/110907720-192b9700-830e-11eb-853e-e707f50cc1f8.png)

La différence est peut-être suffisante pour que ce soit acceptable...

**Comment by GT-CNIG-DDU** [comment]
Pour moi c'est ok. Je ferme la question (issue), quitte à la rouvrir si quelqu'un a une meilleure proposition.

**Comment by alhyss** [comment]
Est-ce que pour clore ce type d'issue, on ne ferait pas mieux d'attendre d'avoir publié sur le GitHub les QML qui implémentent effectivement les symboles ? ça aiderait à s'y retrouver, je pense.

**Comment by GT-CNIG-DDU** [comment]
Tu as tout a fait raison !
Je réouvre la "question en cours"
Arnauld-le-total-newbie

**Comment by cartgab** [comment]
Ce symbole me paraît bien si Jennifer parvient à le reproduire

**Comment by JenniferIGN** [comment]
Oui on peut le reproduire en sld. Pour ce code Pierre Capart nous a indiqué d'afficher comme symbologie le champ TXT (ce sera 'SECT02' par ex), donc on met ce contour avec le champ TXT au milieu? 
@GT-CNIG-DDU

**Comment by alhyss** [comment]
@JenniferIGN @GT-CNIG-DDU Côté QML, et si c'est pertinent, il ne serait pas difficile d'ajouter une étiquette basée sur le champ `TXT` pour ce code.

Mais est-ce vraiment spécifique à ce code ? D'une manière général, le champ `TXT` n'a-t-il pas vocation à contenir les étiquettes des symboles ?

**Comment by JenniferIGN** [comment]
@alhyss @GT-CNIG-DDU Pierre l'avais jugé pertinent dans ce cas précis, peut-être parce que la valeur du champ TXT sera toujours sous la forme SECTnn avec nn des chiffres pour ce code 97-01, ce qui nous permet de faire un contrôle là-dessus dans le GPU avant de l'afficher.

**Comment by GT-CNIG-DDU** [comment]
Je suis d'accord avec Leslie sur l'aspect général du champ TXT.
Ce sujet me fait penser que nous n'avons pas du tout traité la question de la symbolisation textuelle (les étiquettes).
Ma proposition : laissons cela hors de notre périmètre pour le moment, il y a des points prioritaires à traiter. Et bien entendu le projet GPU garde toute latitude pour étiqueter les secteurs de PLUi (couleur,  taille, police utilisée) en sus du contour de secteur, que nous spécifions ici.

**Comment by GT-CNIG-DDU** [comment]
Ceci est un test de réponse directe à un mail de notification de Github

Arnauld Gallais
Expert standardisation et qualification des données géographiques
CEREMA Ouest / DTT / Projet de Territoire et Aménagement
02 40 12 84 76 (sauf jours de télétravail)

**Comment by GT-CNIG-DDU** [comment]
Ceci est un deuxième test de réponse et d'intégration d'un commentaire 
dans une issue Github.

**Comment by alhyss** [comment]
@GT-CNIG-DDU Ok. Dans ce cas on ne prévoirait pas d'étiquette à ce stade dans le QML, parce qu'on considère pour notre part (contrairement au GPU) qu'il n'y a pas lieu d'avoir un traitement spécifique pour ce symbole et que le sujet - pas à l'ordre du jour pour l'heure - sera à terme de définir des spécifications pour l'étiquetage de tous les symboles à partir du champ `TXT`.

Est-ce qu'on fait une _issue_ pour ne pas oublier que le sujet des étiquettes existe (quitte à ne pas y toucher pendant un moment) ou est-ce que c'est prématuré ?

**Comment by GT-CNIG-DDU** [comment]
Exactement !
(Nos commentaires se sont croisés. Le "exactement" était pour la première proposition.)
Pour ma part, pas de nécessité de faire une question sur le sujet des étiquettes pour le moment.

**Comment by alhyss** [comment]
Ok !

**Comment by cartgab** [comment]
Bonjour,
Pour information, le champ TXT, je confirme que le champ TXT est utilisé pour les étiquettes mais aussi pour mettre des informations  que la commune a désiré indiquer dans son PLU. Par exemple pour les ER code 05, le PLU précise le descriptif de l'ER comme la voie concernée.

**Comment by alhyss** [comment]
_Le SG5 du 201.05.04 valide la proposition de symbole._

**Comment by alhyss** [comment]
Avait été pré-implémenté - cf. pull request #22.
