### ISSUE TITLE
Changement de symbole pour INFO 17-00 (plomb)

### ISSUE THREAD

**Issue by cartgab** [cnigfr/DDU-SG5-SYMBOLISATION#20]
Le symbole pb est ambigu. Des élus m'ont posé la question quel était le "problème" sur la commune. 
Une proposition a été faite 
![image](https://user-images.githubusercontent.com/80674754/112476110-d936cc00-8d71-11eb-8eec-449ef17682f6.png)

Symbole ligne de remplissage
>> Angle -15 ; 
>> Séparation 20
>>Largeur contour et ligne 1 ; 
Couleurs RVB 78/78/78 ; 
Si validé, je le traduirais en qml

**Comment by GT-CNIG-DDU** [comment]
Le symbole **pb** est parlant, de plus la présence de plomb peut effectivement être considérée comme un problème puisqu'il s'agit de zones à risque d'exposition au plomb. Pour ces raisons je garderais le symbole actuel.
De plus, au sujet des hachures, cf #16 .

**Comment by cartgab** [comment]
Le plomb n'est pas, à mon sens, un vrai problème étant donné qu'il s'applique à tous le département.
De plus, sa densité fait qu'il masque les autres informations qui elle s'appliquent réellement sur la commune.
Si le "pb" est maintenu, augmenter l'espace entre deux "pb"

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 acte de conserver le symbole actuel en espaçant davantage les poncifs (1 sur 2 ou 1 sur 3 par rapport au figuré actuel)._

**Comment by alhyss** [comment]
Nouveau figuré, avec un espacement doublé entre les symboles de police :

![info_17_espace](https://user-images.githubusercontent.com/55992003/117293287-7c026000-ae71-11eb-9431-94eaf338e772.png)

![plomb_grande_figure](https://user-images.githubusercontent.com/55992003/117293309-80c71400-ae71-11eb-9e93-cf6c557b89d4.png)

```
Motif de points
• déplacement vertical : 25 pt
• distance horizontale : 50 pt
• distance verticale : 50 pt

    Symbole de police
    • caractère(s) : b (unicode 98)
    • couleur de remplissage (RVB) : 52,52,52
    • décalage (en x, en y) : 4,0 pt
    • famille de police : Arial
    • taille : 6 pt

    Symbole de police
    • caractère(s) : P (unicode 80)
    • couleur de remplissage (RVB) : 52,52,52
    • famille de police : Arial
    • taille : 6 pt

Ligne simple
• couleur (RVB) : 52,52,52
• largeur de trait : 1 pt
• style de trait : ligne continue
```

Accessoirement, j'ai nettement amélioré la manière dont ce symbole était décrit/implémenté - superposer quatre motifs de points quand un seul suffisait ne paraissait pas très heureux.

Est-ce que ça vous va comme ça, ou espace-t-on encore davantage les symboles de police ?

**Comment by GT-CNIG-DDU** [comment]
Ok pour moi, voire légèrement plus espacé, mais c'est à @cartgab et @JenniferIGN de dire.

**Comment by cartgab** [comment]
Je n'aime pas ce symbole . Superposant le zonage (avec ses étiquettes) le texte "pb" pose problème et rend la carte plus difficile à lire. 
Je n'apliquerai pas ce symbole donc pas d'avis.
