### ISSUE TITLE
Changement couleur symbole PSC 16-00, 16-04 et 16-05

### ISSUE THREAD

**Issue by cartgab** [cnigfr/DDU-SG5-SYMBOLISATION#21]
Désolée, j'ai oublié d'en parlé lors de la dernière réunion.
Le symbole couleur jaune est difficilement visible en zone agricole car le zonage est également jaune. 
Est proposé le même symbole avec la couleur RVB 255/170/0 (orangé)
![image](https://user-images.githubusercontent.com/80674754/112475882-97a62100-8d71-11eb-87f8-421bfa7cb317.png)

**Comment by alhyss** [comment]
@cartgab Je rate sûrement quelque chose, mais avec les prescriptions qui ne s'affichent qu'à partir du 1:2500 et les zones qui ne sont plus représentées que par des contours au-delà du 1:2500, la superposition des deux est-elles vraiment un sujet ?

**Comment by cartgab** [comment]
Ta remarque est juste mais dans tous les cas le jaune ne ne paraît pas une couleur très visible. 
Comment envisage-tu dans ces conditions l'impression des plans à partir du standard ? ou cet usage ne fait-il pas objet de ce standard?

**Comment by GT-CNIG-DDU** [comment]
Si la superposition des deux n'est pas forcément un sujet (j'écris prudemment "pas forcément" car s'il ne l'est effectivement pas à l'écran avec nos spécifications il peut l'être pour un tirage papier si la collectivité décide de colorier ces zonages en aplat, mais alors @cartgab je renouvelle ma demande de pouvoir disposer d'un aperçu des sorties graphiques de Rambouillet Territoire) je suis d'accord avec la remarque de @cartgab sur la difficulté de visualiser un poncif en jaune, y compris sur un fond gris :
![2021-04-22_113408](https://user-images.githubusercontent.com/79853274/115691982-d8885a00-a35e-11eb-9227-6fcc9068e039.jpg)
Comme il s'agit (hors PRESC 16-03 STECAL) de constructions et installations nécessaires à des équipements collectifs en zone A ou N je ne serais pas choqué par une couleur plus soutenue et contrastée avec le jaune 255/255/0 et le vert 86/170/2.
Pour ces raisons je suis favorable à la couleur proposée par @cartgab RVB 255/170/0 (orangé)

**Comment by cartgab** [comment]
Le premier PLU de la commune Orphin sont téléchargeables depuis https://we.tl/t-s5WjAkBp8Q.
Orphin est la première commune qui applique la charte de RT (qui prend en compte les spécifications) sur son plan de zonage !
En effet, l'application de ces spécifications n'est possible que lors d'une modification ou révision d'un PLU.

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 adopte la proposition de changement de couleur._
