### ISSUE TITLE
Définition de spécifications pour les étiquettes des zones

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#23]
Le guide *[Spécifications de symbolisation des documents d'urbanisme](https://drive.google.com/drive/folders/1YHCxmiWknRLXUREbOYq4CUpvqYGZaw2Z)* prévoit explicitement que les zones soient étiquetées à partir du champ `libelle`, toutefois aucune spécification n'a été définie si ce n'est pour leur couleur (= blanc + tampon de la couleur associée au `typezone`)  : police, taille, largeur du tampon, voire des paramètres sans doute beaucoup plus dépendants du système comme le placement, la répétition éventuelle dans les grandes zones...

Les QML actuellement publiés contiennent des étiquettes pour les zones, mais il n'y a pas de description littérale de leur paramétrage dans *[preconisations.md](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/SYMBOLISATION/PLU/preconisations.md).*
![zone_urba](https://user-images.githubusercontent.com/55992003/112524895-9dffc180-8da0-11eb-804b-90cc5cd99578.png)
*à toute fin utile : Century Gothic, Gras, taille 14pt, tampon de taille 3pt, position "horizontal", valeurs par défaut pour le reste*

Autre aspect, la gestion des étiquettes dans les QML est comparable à celle des symboles (ça reste du XML dans les deux cas), mais il y a des différences qui font qu'il ne sera pas complètement trivial de transposer les fonctions qui écrivent les descriptifs des symboles au cas des étiquettes.

**Comment by GT-CNIG-DDU** [comment]
Pensons à relancer Marie pour qu'elle nous indique les spécifications utilisées dans la maquette sur Nice.

**Comment by GT-CNIG-DDU** [comment]
Il me semble que le GPU répète régulièrement l'étiquette du LIBELLE de zone pour une grande surface et/ou à grande échelle.
@JenniferIGN peux-tu nous indiquer les spécifications de répétition de l'étiquette  ?

**Comment by GT-CNIG-DDU** [comment]
_"'il ne sera pas complètement trivial de transposer les fonctions qui écrivent les descriptifs des symboles au cas des étiquettes"_
@alhyss : dans ce cas on n'est peut-être pas forcé de l'automatiser en SQL pour les étiquettes.
Ce descriptif ne peut-il pas à  être mis dans une rubrique dédiée "étiquette de zonage" avec des spécifications rédigées manuellement ? (je pose juste la question car j'avoue que je ne mesure pas les impacts...)

**Comment by JenniferIGN** [comment]
> 
> 
> Il me semble que le GPU répète régulièrement l'étiquette du LIBELLE de zone pour une grande surface et/ou à grande échelle.
> @JenniferIGN peux-tu nous indiquer les spécifications de répétition de l'étiquette ?

Sur le GPU l'étiquette du zonage est affiché une fois par tuile de 256*256 pixels, c'est pour cela qu'on peut la retrouver plusieurs fois sur un zonage qui a une grande surface.

**Comment by GT-CNIG-DDU** [comment]
@alhyss 
- J'ai relancé Marie ce jour sur les spécifications des étiquettes.
- Le remplissage de la zone par répétition des étiquettes est un vrai sujet, @JenniferIGN nous a indiqué la solution geoserver (merci), existera-t-il une solution pour QGIS / QML ?

**Comment by GT-CNIG-DDU** [comment]
- Pour les zones de type A..gricole : plutôt le caractère A de couleur noire dans son halo jaune, afin d'améliorer la visibilité ?
Comme dans la maquette de Nice : 
![2021-03-31_163201](https://user-images.githubusercontent.com/79853274/113161413-a6dc1180-923e-11eb-8daf-0a3475806b7c.jpg)

**Comment by alhyss** [comment]
Ok pour le texte noir de la zone A.

Il n'y a pas de notion de répétition dans QGIS pour les étiquettes des entités surfaciques (seulement pour les entités linéaires). Ce qu'évoque Jennifer reviendrait plutôt à gérer l'étiquette comme un symbole et pas à proprement parler comme une étiquette, mais ce serait possible en procédant ainsi, oui.

Il faut savoir ce que nous voulons obtenir, cependant. Même si les étiquettes ne peuvent pas être répétées, elles bénéficient de mécaniques pour optimiser leur placement qui font qu'il y aura toujours une étiquette visible par zone affichée sur la carte, et pas planquée dans un coin et à demi coupée par la limite de zone comme ça pourrait se produire avec une gestion sous forme de poncif. Je ne me rends pas compte des implications, cependant.

**Comment by GT-CNIG-DDU** [comment]
Si les étiquettes peuvent bénéficier d'optimisation de placement qui font qu'il y aura toujours une étiquette visible par zone affichée sur la carte, et pas planquée dans un coin et à demi coupée par la limite de zone : alors c'est parfait !

**Comment by GT-CNIG-DDU** [comment]
Je reproduis ici les spécifications transmises par Marie (par mail) concernant les étiquettes :
Les étiquettes sont en police blanche ou noire en fonction de la couleur de contour
Avec un halo qui reprend la symbologie de la zone étiquetée.
Police Arial gras
Taille 22 pt
Taille du halo : 3 pt

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 valide les spécifications ci-avant (Arial gras, 22pt, tampon de 3pt)._

**Comment by alhyss** [comment]
NB. J'avais oublié cette issue dans l'ordre du jour de ce matin, mais elle a été traitée en même temps que l'issue #27.

**Comment by alhyss** [comment]
_Les modifications des symboles ont été implémentées par le pull request #35._

Reste à faire : expliciter les spécifications relatives aux étiquettes dans le récapitulatif Markdown.
