### ISSUE TITLE
Usage des labels dans les issues

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#24]
Quelques propositions que je voulais soumettre à discussion.

Comme vu l'aurez peut-être noté, j'ai créé quatre labels personnalisés, en plus des labels par défaut de GitHub : **`PLU`**, **`PSMV`**, **`à valider SG5`** et **`valider SG5`**.

J'avais en tête que nous pourrions en faire l'usage suivant :

1. Utiliser le label **`PLU`** quand il est question des préconisations de symbologie associées au standard PLU et le label **`PSMV`** pour les préconisations spécifiques au standard PSMV ou les problématiques liées à l'usage des préconisations PLU pour des PSMV.

Ça aidera à s'y retrouver pour l'implémentation, vu qu'on a d'un côté des outils (projet QGIS, QML, etc.) pour les PLU et de l'autre des outils pour les PSMV. 

2. Pour les issues qui portent sur des points nécessitant une décision formelle du SG5 (en premier lieu tout ce qui touche aux spécifications de symbologie, pour le reste ce sera sans doute à déterminer au cas par cas), quand il y a de la matière (des solutions ont été avancées) **et seulement une fois que tout le monde a eu le temps de s'exprimer**, de faire ses propositions, contre-propositions, etc, utiliser le label  **`à valider SG5`** pour montrer que le sujet est désormais mûr pour être examiné en réunion.

Tel que je le vois, ce label doit nous permettre d'établir l'ordre du jour des réunions du sous-groupe.

3. Utiliser le label **`validé SG5`** pour ces mêmes issues une fois qu'elles ont fait l'objet d'une décision en réunion du SG5, ainsi que pour les autres points qui ne faisaient pas l'objet d'issues, mais sur lesquelles une décision a été prise et qui appellent une action vis-à-vis des outils publiés sur le GitHub (il serait bien que tous ces points soient a posteriori traduits en issues).

Ce label doit permettre d'identifier rapidement toutes les propositions prêtes à être implémentées.

4. Être parcimonieux sur l'usage des autres labels.

Visuellement, il est plus facile de s'y retrouver quand on n'utilise qu'un petit nombre de couleurs... du moins c'est mon avis, je ne sais pas s'il est partagé. Surtout, je pense que les labels n'ont pas d'intérêt s'ils servent juste à décorer les issues, il faut qu'ils nous apportent quelque chose derrière.

Pour discussion critique, donc, et, si vous adhérez à la logique, vous verrez sans doute d'autres labels utiles auxquels je n'ai pas pensé...

**Comment by GT-CNIG-DDU** [comment]
Je suis d'accord avec ces propositions qui ont le mérite d'établir automatiquement une partie de l'ordre du jour du SG5.

Ce qui implique désormais d'échanger sur les spécifications via le Github plutôt que par mail.

J'ai créé un label "à explorer" (non, ne me tape pas sur les doigts @alhyss 😂) je ne sais plus pour quel issue, mais à ce moment-là il me semblait intéressant...

**Comment by alhyss** [comment]
@GT-CNIG-DDU Pour la #15. Et il a le mérite de montrer que c'est un sujet sur lequel nous n'envisageons pas de décision à court terme.

Ce sont surtout les labels par défaut dont je ne suis pas sûre de la plus-value - mais je dis ça après en avoir mis partout, puis les avoir tous enlevés :D

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 valide la proposition._

**Comment by alhyss** [comment]
À faire : formaliser cet usage des étiquettes dans un fichier `contributing.md`.

**Comment by nkulpinski** [comment]
Dans le cas où le catalogue serait finalement simplement le Github, et les contibution gérées via un formulaire dans les issues, il faudrait mettre en place ma prise en compte dans le GPU comme label avec un système d'ordre
à valider SG5 --> validé SG5 --> GPU --> GPU ok ------> clôture de l'issue
