### ISSUE TITLE
Définition de spécifications pour les contours de zones (à grande échelle)

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [cnigfr/DDU-SG5-SYMBOLISATION#27]
Spécifions également les contours de zones à grande échelle car ils sont décalés à l'intérieur de la zone pour éviter leur superposition.
En voici un exemple : 
![2021-03-31_154134](https://user-images.githubusercontent.com/79853274/113153710-a8560b80-9237-11eb-8892-b345cadbc3a3.jpg)

**Comment by alhyss** [comment]
Proposition de spécification, sur la base de ce qui avait été fait pour le [prototype basé sur le PLU de Nice](https://esrifrance.maps.arcgis.com/apps/webappviewer/index.html?id=8563c522029b46e0b6221847d7aca94c) :
```
Ligne simple
• couleur (RVB) : 35,166,0
• décalage : 3.5 pt
• largeur de trait : 7 pt
• style de jointure : rond
• style de trait : ligne continue

Ligne simple
• couleur (RVB) : 99,99,99
• largeur de trait : 1.5 pt
• style de trait : ligne continue
```

On passerait de :
![zone_urba](https://user-images.githubusercontent.com/55992003/113157388-236cf100-923b-11eb-9a8c-1e80c561dd24.png)

à :
![zone_urba_avec_decalage](https://user-images.githubusercontent.com/55992003/113157370-1ea83d00-923b-11eb-8971-2c89c2f55e5d.png)

La ligne grise est sur le contour du polygone, la ligne colorée est décalée vers l'intérieur d'une demi-épaisseur de trait.

**Comment by GT-CNIG-DDU** [comment]
C'est ok pour moi pour les contours !

Cf remarque dans #23 sur la couleur de la lettre pour TYPEZONE = 'A' (blanc => noir, pour une meilleure visibilité)

**Comment by GT-CNIG-DDU** [comment]
Je reproduis ici les spécifications transmises par Marie (par mail) pour le contour : 
- un trait fin gris foncé (52/52/52) de largeur de 2.5pt permettant de séparer les zones adjacentes
- un second contour décalé de 3 pt et dont l’épaisseur est de 7pt, coloré de la couleur de la zone

**Comment by nkulpinski** [comment]
C'est à peu de chose près ce que nous faisons, mais nous avons mis une transparence sur la couleur pour ne pas se retrouver avec des infos cachées par le trait de zone qui du coup est bien plus épais que necessaire

**Comment by cartgab** [comment]
Sur les applications publiées dédiées à l'urbanisme, j'applique un contour de couleur identique à  tous les zonages afin de séparer les zones et de ne pas masquer des informations.

**Comment by alhyss** [comment]
Pour mémoire, spécifications fournies par Marie pour les caractères :

> Police Arial gras
> Taille 22 pt
> Taille du halo : 3 pt

**Comment by alhyss** [comment]
Avec les valeurs fournies par Marie pour le texte et les contours :

![zones_mt](https://user-images.githubusercontent.com/55992003/116970408-3cdcdf00-acb8-11eb-9eaf-8b32836de658.png)

Exemple de spécifications littérales pour la zone AUc :
```
Ligne simple
• couleur (RVB) : 212,0,6
• décalage : 3 pt
• largeur de trait : 7 pt
• style de jointure : rond
• style de trait : ligne continue

Ligne simple
• couleur (RVB) : 52,52,52
• largeur de trait : 2.5 pt
• style de trait : ligne continue
```

Pour la transparence, ça mérite sans doute d'être discuté. Ayant toujours mis la couche des zones en dessous des autres, je ne voyais pas vraiment les superpositions comme un problème, à vrai dire.

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 valide la proposition._
