### ISSUE TITLE
Amélioration de la représentation des zones à petite échelle

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#28]
Deux propositions :
1. passer l'opacité de 40% à 60% ;
2. remplacer les contours colorés par des contours gris foncé ou noirs.

La première proposition relève plus de la correction que d'autre chose. Le guide dit "avec un effet de transparence à 60 %" et j'avais interprété ça comme 60% de transparence, donc 40% d'opacité, mais c'était une erreur de ma part. Sur le GPU, c'est visiblement une opacité de 60% qui est appliquée, idem pour les illustrations du guide, et à 40% les tons de rouge et rose commencent à être difficiles à distinguer.

La seconde proposition part du constat que, comme à grande échelle (cf #27), les bordures colorées des zones se recouvrent arbitrairement, ce qui n'est pas très esthétique et peut rendre certaines zones - celles dont les contours ont été mangés - moins visibles que d'autres.

ex :
![zones_reel_couleur](https://user-images.githubusercontent.com/55992003/113321793-3d2e3700-9314-11eb-8907-a2911ba63cbe.png)

Il est important d'avoir des contours clairement perceptibles, dans la mesure où deux zones peuvent avoir le même `typezone` et donc la même couleur, mais des libellés différents. Par contre je ne vois pas ce qu'apporte le fait de colorer les contours, dans la mesure où la couleur de l'aplat est porteuse de la même information. D'où la proposition d'utiliser une seule couleur pour tous les contours de zones. Un gris foncé ou du noir me semble tout indiqué - c'est neutre et ça tranchera avec les aplats.

ex (avec du gris) :
![zones_reel_gris](https://user-images.githubusercontent.com/55992003/113322721-57b4e000-9315-11eb-8736-4f0937ea8c74.png)

C'est, soit dit en passant, déjà ce que fait le GPU :
![zones_gpu](https://user-images.githubusercontent.com/55992003/113323510-5506ba80-9316-11eb-9833-1a1e60b639c2.png)

**Comment by GT-CNIG-DDU** [comment]
- Proposition 1 : Pour ma part une grosse préférence pour les couleurs atténuées. Ceci étant dit nous pouvons relativiser cette question car :
a) c'est tout à fait subjectif (les goûts et les couleurs...)
b) peu important car les outils (même le GPU) donnent à l'utilisateur la possibilité de régler ce paramètre à sa convenance.
c) on peut faire fifty fifty, Ce qui a le mérite de ne pas préciser si on parle de transparence ou d'opacité 😉

- Proposition 2 : ok pour remplacer les contours colorés par des contours gris foncé. Mais plutôt pas en noir (couleur utilisée par des symbolisations par défaut...)

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 valide les deux propositions (opacité à 60% et contours gris). Le document général sur les spécifications devra être amendé en conséquence._
