### ISSUE TITLE
Exemples de symbolisation

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [cnigfr/DDU-SG5-SYMBOLISATION#29]
La symbolisation du PLUi de Rennes Métropole est intéressante : 
un fond topo / parcellaire gris ; des zonages en couleurs ; et toutes les prescriptions / informations sont traitées en noir : https://mviewer.sig.rennesmetropole.fr/?config=apps/PLUi/PLUi.xml#
![2021-04-08_160755 rennes](https://user-images.githubusercontent.com/79853274/114161588-8b50c500-9928-11eb-9e2c-7231774e6ae0.jpg)

**Comment by nkulpinski** [comment]
Voici également pour exemple la symbolisation du PLUi du territoire Marseille Provence de la Métropole Aix Marseille Provence
[https://sig.ampmetropole.fr/webportal/apps/webappviewer/index.html?id=1fecb1a7ddd740ef88ffdc98c1583382](https://sig.ampmetropole.fr/webportal/apps/webappviewer/index.html?id=1fecb1a7ddd740ef88ffdc98c1583382)
Le service de carte est en train d'être optimisé pour qu'il soit plus rapide à l'affichage ;)
![2021-04-08_152407 marseille](https://user-images.githubusercontent.com/79853274/114161666-a1f71c00-9928-11eb-88b0-3f6b4b86678b.jpg)
