### ISSUE TITLE
Création d'un symbole pour l'information 98-00 du standard PLU

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#3]
Information "_Périmètre d’annulation partielle du document d’urbanisme (lorsqu’elle impacte le règlement graphique)_", introduite par la version 2017b du standard PLU.

**Comment by cartgab** [comment]
Je n'ai pas compris comment a été créé ce nouveau code.
Je ne sais pas ce qui est mis dedans, Pourrais-je avoir une exemple d'application ?

**Comment by GT-CNIG-DDU** [comment]
@cartgab : cf. le standard CNIG PLU. INFO 98-00 : _Périmètre d’annulation partielle du document d’urbanisme (lorsqu’elle impacte le règlement graphique)_, introduite par la version 2017b du standard PLU, (comme écrit par @alhyss dans son post)

**Comment by cartgab** [comment]
C'est au -delà de mes compétences en urbanisme, je ne vois pas de cas pratique.

**Comment by GT-CNIG-DDU** [comment]
Pour INFO 98-00 : Périmètre d’annulation partielle du document d’urbanisme (lorsqu’elle impacte le règlement graphique)
Pour le coup j'imaginerais bien un aplat très occultant (blanc opaque ? ou teinte légère mais opaque ?) pour indiquer que le PLU est annulé à cet endroit. 
@JenniferIGN : peut-on s'inspirer de la symbolisation du GPU ? Quelle est-elle pour les annulations partielles ?

**Comment by alhyss** [comment]
Gris clair ? On a déjà l'information 31-00 qui utilise un aplat blanc :

![INFO-31-00](https://user-images.githubusercontent.com/55992003/113143192-290f0a80-922c-11eb-9ef9-0bdd3ec2044e.png)

Mais je m'interroge sur la transparence de couche des informations surfaciques. Avec une opacité à 60%, jamais le 98-00 ne sera véritablement occultant (et ce n'est pas ça non plus qui aidera à distinguer un aplat blanc d'un aplat gris clair)...

**Comment by GT-CNIG-DDU** [comment]
Ah oui.. la transparence : je n'y avais pas pensé.
Par contre j'imaginais un aplat avec une teinte assez forte / "visible" (et maintenant : d'autant plus que je sais qu'elle sera atténuée par la transparence)

**Comment by alhyss** [comment]
Noir ?

```
Remplissage simple
• couleur de remplissage (RVB) : 0,0,0
```

![98_noir](https://user-images.githubusercontent.com/55992003/113164335-4f8b7080-9241-11eb-89a2-345366657bd9.png)

Ou un gris foncé si c'est trop brutal.

**Comment by GT-CNIG-DDU** [comment]
Oui oui oui le retour du caviardage digne de la période de la guerre froide : trop bien !
Oui mais bon sinon tu pourrais pas nous faire une zone plutôt en tenue de camouflage, hein dis dis 🤪 ?
![2021-03-31_170648](https://user-images.githubusercontent.com/79853274/113168690-2cfb5680-9245-11eb-90dc-7b9223e68c43.jpg)

Bon ok je sors : 🚪 et j'éteins mon 💻

**Comment by GT-CNIG-DDU** [comment]
Trêve de plaisanterie, le gris foncé me va bien. J'avais pensé à une couleur lie de vin aussi 
![2021-03-31_172432](https://user-images.githubusercontent.com/79853274/113169529-fb36bf80-9245-11eb-9317-a4905998b421.jpg)

**Comment by alhyss** [comment]
@GT-CNIG-DDU En fait, sur la vignette c'était du noir avec 40% de transparence de couche, pas du gris foncé. On est-ce que tu veux dire que tu préfères du gris foncé à ça ?

**Comment by GT-CNIG-DDU** [comment]
Oui j'avais bien compris : noir à 40%. Et c'est ok pour moi. Voir simplement si on veut mettre une teinte ou pas.

**Comment by JenniferIGN** [comment]
@GT-CNIG-DDU Sur le GPU ils sont représentés par un aplat noir (un genre de caviardage), aucun souci pour s'en inspirer.

**Comment by alhyss** [comment]
_Le SG5 du 2021.05.04 valide le symbole avec un aplat noir._
