### ISSUE TITLE
Quels types de géométries pour les postes de la légende PSMV  

### ISSUE THREAD

**Issue by Laetitia-aga** [cnigfr/DDU-SG5-SYMBOLISATION#30]
il faudrait préciser dans le document "standard CNIG PSMV (v2019-novembre 2019) dans quelle table se trouve les certaines prescription : prescription ponctuelle, linéaire ou surfacique). Je me suis posée la question pour plusieurs symboles :

* code <01-01>  
* code <18-00> à <18-05> : Les OAP. Peut-etre faudrait-il rajouter dans le style, l'affichage de l'étiquette <LIBELLE> nommant l'OAP ? 
* code <40-50>

**Comment by GT-CNIG-DDU** [comment]
Pour la PRESC 40-50 spécifique aux PSMV, cf. issue #11 en cours (besoin de consulter le Ministère de la Culture)
Pour les PRESC 01-01 et 18-00à05 : le standard PLU admet par défaut les trois primitives graphiques pour l'ensemble des prescriptions et informations, mais en pratique la symbolisation est présentée dans le [projet QGIS de symbolisation PLU](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/SYMBOLISATION/PLU/projet_qgis_symbolisation_plu.zip), ou plus simplement dans les pdf de type "planche contact" mentionnés à l'issue #26 que l'on retrouve dans les [Spécifications de symbolisation des documents d’urbanisme](https://drive.google.com/drive/folders/1YHCxmiWknRLXUREbOYq4CUpvqYGZaw2Z) (page 11)

**Comment by alhyss** [comment]
C'est vrai qu'il y a une ambiguïté sur les symboles de la partie _I - Limites_ de la [légende](https://www.legifrance.gouv.fr/download/pdf?id=yqIzofjb3_1qq9uXOxmBuG5X-5d7dJHwKZsEdIOVbh8=). Ces périmètres sont représentés dans la légende sous forme de traits, comme s'il s'agissait de linéaires, mais ce sont nécessairement des formes fermées et, pour une implémentation web, il peut être préférable de passer par des surfaces, ne serait-ce que pour les fonctionnalités d'interrogation (quand on clique sur la surface, ça renvoie quelque chose, pour un linéaire il faut généralement cliquer sur la ligne elle-même).

Actuellement, les spécifications PSMV prévoient les deux possibilités, linéaire ou surfacique, avec exactement le même symbole pour la ligne du linéaire et celle du contour du surfacique. À mon avis, c'est une bonne chose. @Laetitia-aga est-ce que tu aurais voulu une recommandation quelque part dans le standard sur le fait de privilégier des polygones ?

Accessoirement, @Laetitia-aga est-ce que tu verrais un problème à renommer ton issue "_Quels types de géométries pour les postes de la légende PSMV ?_" ou quelque chose comme ça ? Il me semble que ce serait plus clair.

**Comment by Laetitia-aga** [comment]
@alhyss, je pense qu'il faut penser aux novices en géomatique et préciser tout ce qui peut l'être. Après si le document "standard CNIG PSMV", s'accompagne par le projet QGIS (comme celui que tu as fait pour le PLU), alors la précision n'est peut-être pas nécessaire. 

Je suis désolée pour les termes employés qui ne sont pas toujours précis mais le language "géomatique" m'est parfois étranger... 

J'ai donc renommé l'issue, n'hésitez pas à modifier mes commentaires avec le bon vocabulaire

**Comment by GT-CNIG-DDU** [comment]
Je ne m'étais pas posé la question jusque-là, considérant que la légende nationale différenciait bien les symbolisations surfaciques (un rectangle symbolisant le périmètre et son contenu), linéaires et ponctuelles.
La partie I-1 est hors périmètre du standard, tant mieux. La partie I-2 est effectivement plus ambigüe : dans la logique précitée ce sont bien des linéaires mais le petit 24 en fin de légende pour les OAP tend bien à dire le contraire et @alhyss aussi, ce qui serait de plus cohérent avec la symbolisation des PRESC 18 dans la partie PLU.
_Conclusion : méfions-nous toujours des notes de bas de pages et des alinéas illisibles en fin de contrat_ 🤦‍♂️
Bon, trêve de plaisanterie, quelles sont vos propositions (surfacique ou linéaire) pour ces trois symboles du I-2 et voyez-vous d'autres cas à trancher ?
Ma proposition : ajouter sous ces trois symbolisations la mention : "Ces trois symboles correspondent à la symbolisation des périmètres des surfaces concernées". _Ou alors on le met en note de bas de page ?_ 👀🤣

**Comment by alhyss** [comment]
Pour moi, la légende donne une obligation de résultat visuel, elle n'impose pas en elle-même un type de géométrie plutôt qu'un autre.

Je trouve les surfaciques plus logique sur le fond pour les trois postes, considérant que les règles/informations afférentes s'appliquent à tout ce qui est à l'intérieur du périmètre et pas juste là où passe le trait.

Mais je vois au moins une bonne raison d'utiliser des linéaires (et pas forcément fermés, en fait, contrairement à ce que je disais tout à l'heure...), notamment lorsque le principal objectif est une sortie PDF/papier des documents : éviter le problème des superpositions des contours pour les surfaces voisines. Avec les tirets, qui seront toujours décalés d'un contour à l'autre puisqu'ils sont positionnés à partir du premier nœud de la ligne, le résultat est atroce.

Ce sera particulièrement prégnant pour les zones, puisqu'il y aura presque nécessairement des juxtapositions, sauf à n'avoir qu'une seule zone.

Pour les PLU, le choix a été fait de décaler les contours des zones vers l'intérieur, mais ça serait bizarre ici, puisque toutes les zones sont de la même couleur... Deux pointillés violets identiques côte à côte, je ne sais pas si ça rime à quelque chose. En tout cas, je pourrais comprendre que certains préfèrent utiliser des linéaires à cause de ça (avec une seule géométrie aux frontières, évidemment).

Personnellement, j'ai l'habitude de tricher en doublant tous mes contours pointillés par des lignes blanches qui cachent la ligne du dessous (ligne blanche 1 - ligne pointillé 1 - ligne blanche 2 qui masque ligne pointillé 1 - ligne pointillée 2 - etc). Nous pourrions envisager d'utiliser ça pour les préconisations PSMV. Mais ce n'est pas très discret quand le fond n'est pas blanc.

Accessoirement, je viens de remarquer que les préconisations de symbolisation actuelles ne mentionnent pas les zones... Une raison à ça ?

**Comment by GT-CNIG-DDU** [comment]
Quand tu parles des zones tu parles des OAP ? On souhaite pouvoir les interroger à l'écran => surfacique.

Les usages écran et papier peuvent générer des contraintes spécifiques. Je rappelle que l'on se concentre prioritairement sur l'usage écran parce qu'il est prégnant et suscite un besoin de spécification et d'harmonisation. Accessoirement parce qu'avec nos faibles ressources nous aurions un peu de mal à poursuivre deux lièvres à la fois...

L'usage papier connaît moins ce besoin d'harmonisation (imposée par la notion de continuum géographique liée à l'usage écran), et les utilisateurs n'ont heureusement pas attendu les travaux du CNIG pour réaliser leurs sorties graphiques papier. D'un autre côté il est plus exigeant sur le plan esthétique, et sur le plan sémiologique dans la mesure où l'on peut interroger l'écran mais pas le papier. Il y a un aspect pour lequel il se montre plus simple : il n'y a pas à gérer de variation de la symbolisation suivant l'échelle puisqu'il n'y en a qu'une.

Je n'ai pas compris la dernière phrase et la question.

**Comment by alhyss** [comment]
@GT-CNIG-DDU Désolée, ce n'était visiblement pas clair du tout.

Quand je parle de "zones", je parle des zones du plan de zonage, qui (sauf erreur de ma part) se trouvent être représentées de la même façon que les OAP dans la légende nationale :
![legende_psmv_zones](https://user-images.githubusercontent.com/55992003/115507873-f67d8e00-a27c-11eb-8379-68af4e62899e.png)

(on pourrait imaginer qu'il s'agit d'un autre genre de "zone", mais ça impliquerait que la légende nationale PSMV n'ait pas prévu de figuré pour les zones du zonage, ce qui me semble inconcevable)

Sauf à ce que je l'aie ratée (ce qui serait tout à fait possible), je ne crois pas que cette représentation des zones ait été reprise dans les préconisations de symbolisation PSMV actuelles et je me demandais pourquoi.

Sinon, mon propos était plutôt que certains PSMV risquent d'avoir en amont fait le choix d'utiliser des géométries linéaires pour leurs "limites", par exemple pour les raisons que j'évoque. Nous pouvons alerter sur le fait qu'il est préférable d'avoir des polygones, je suis tout à fait d'accord, mais ça pose la question du maintient des préconisations de symbolisation pour les géométries linéaires : est-ce qu'il en faut parce qu'il y aura sans doute des géométries linéaires et qu'il est toujours délicat de modifier a posteriori les géométries d'un document potentiellement approuvé, ou est-ce qu'il n'en faut pas parce que ça incite à utiliser des géométries linéaires qui poseront problème pour l'interrogation des couches ?

Et je ne pense pas que nous puissions ignorer complètement la question des superpositions pour une représentation écran. Notamment, les limites de PVAP et les limites de zones/OAP utilisent des lignes de même couleur et même épaisseur de trait avec simplement des motifs de tirets différents. Si les motifs ne sont pas lisibles à cause des chevauchements, on ne saura plus à quoi correspondant la limite. Certes, il restera généralement possible d'aller interroger les données, mais ça n'empêche pas d'essayer d'optimiser la visualisation (et je parle là surtout des spécifications pour les géométries surfaciques) - comme nous l'avons fait pour les zones des PLU avec le décalage des contours vers l'intérieur.

**Comment by GT-CNIG-DDU** [comment]
Ah oui, j'avoue que je n'avais pas tilté pour les zones. Question : un PSMV ne correspond-il pas en général à une zone U libellée PSMV (plus éventuellement des zones "naturelles") ? Je doute qu'il y ait de nombreuses zones dans son périmètre.
Dans les questions que tu cites, le mieux est je pense d'observer des cas et des rendus graphiques concrets. @Laetitia-aga nous apportera son éclairage pour le PSMV de Strasbourg.
J'ai également demandé hier à Besançon des sorties graphiques de leurs PSMV pour voir comment ils ont traité le zonage+OAP et ce que cela donne graphiquement. Nadège ne répond pas à l'invitation au Github, mais je vais inviter Dominique.

**Comment by alhyss** [comment]
Je ne pense pas non plus qu'il y ait beaucoup de zones dans les PSMV d'une manière générale - en tout cas pas dans ceux que je suis allée voir quand on travaillait sur le standard, puis sur les recommandations de mises en oeuvre.

Mais il peut y en avoir plus d'une, et ça arrive en pratique. Par exemple, le PSMV du VIIe arrondissement de Paris a une zone US "_zone urbaine sauvegardée_" et une zone UVS "_zone urbaine verte sauvegardée_". Dans leur règlement graphique (antérieur à la légende nationale), il y a un figuré pour la zone UVS et la zone US est définie comme "_le territoire du secteur sauvegardé non inclus aux documents graphiques dans la zone UVS_". En pratique, ça revient pour eux à n'avoir qu'une seule zone modélisée et ça ne poserait pas de problème vis-à-vis de la légende nationale. Mais s'ils voulaient standardiser, il faudrait qu'ils créent des données pour la zone US, puisque le standard PLU impose au zonage de couvrir tout le territoire...

**Comment by GT-CNIG-DDU** [comment]
Très bien. Cela fait donc effectivement deux zones. Mais revenons à la question initiale de cet issue _"quel type de géométrie ?"_ tu as écrit :
_"Pour moi, la légende donne une obligation de résultat visuel, elle n'impose pas en elle-même un type de géométrie plutôt qu'un autre."_ => nous sommes entièrement d'accord.
_"Je trouve les surfaciques plus logique sur le fond pour les trois postes, considérant que les règles/informations afférentes s'appliquent à tout ce qui est à l'intérieur du périmètre et pas juste là où passe le trait."_ => Idem pour moi.
Après, peuvent éventuellement se poser des questions esthétiques de superposition du symbole tireté de la légende nationale à la jointure de deux zones ou OAP. Les moteurs graphiques des SIG ne savent-ils pas gérer cela ? Personnellement je ne sais pas y répondre mais j'espère pouvoir en juger à travers les exemples produits par Besançon et Strasbourg qui respectent cette légende. L'exemple de Paris sera évidemment intéressant aussi.

**Comment by alhyss** [comment]
J'ajoute cette issue à l'ordre du jour du prochain SG5 (projet [SG5 2021.09.07](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/projects/3)).

Au final, la question à trancher est : faut-il proposer des symboles linéaires pour les codes PSMV [PSC 18](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#prescription-18-00) (vaut aussi pour les [zones](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#zones)), [PSC 07-69](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#prescription-07-69) et [INFO 01-01](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#information-01-01), en partant du principe que certains pourraient en avoir besoin ou ne pas le faire parce que ça encourage une mauvaise pratique ?

Je ne l'ai pas fait dans la proposition qui se trouve actuellement sur la branche [beta](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/tree/beta).

![psmv_psc_18](https://user-images.githubusercontent.com/55992003/130433891-702506e0-4765-47f2-822d-97caec1a662c.png) ![psmv_psc_07_69](https://user-images.githubusercontent.com/55992003/130433971-02da74ed-428a-46e9-a3c7-ff9e7ecca143.png) ![psmv_info_01](https://user-images.githubusercontent.com/55992003/130434085-58e4604a-3bd1-4b34-a0de-cdcb60a70300.png)

Par contre, j'ai proposé les deux formes pour les codes [PSC 15-50 à 51](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#prescription-15-50) et [PSC 39-50 à 52](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#prescription-39-50), parce qu'il me semble que les deux ont un sens sur le fond. Si on prend l'exemple du 39-50 *Hauteur maximale de façade*, j'imagine qu'on aurait :
- du surfacique pour une règle qui s'applique à tout un îlot (et vaudrait aussi pour les façade sur cour intérieur, etc.) ;
- du linéaire pour une règle qui ne concerne que les façades sur lesquelles passe la ligne.

![PSC-39-50](https://user-images.githubusercontent.com/55992003/130435008-19d9ba4b-4400-44cf-8e50-76d4dbdbf95c.png)

Dans le même esprit, pour les codes [INFO 70-00](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#information-70-00), [PSC 07-51](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#prescription-07-51) et [PSC 03-50](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#prescription-03-50), j'ai proposé à la fois un style pour les géométries ponctuelles et les géométries surfaciques (symbole ponctuel sur le centroïde), car il me semble tout à fait entendable que la géométrie soit celle du bâtiment ou de l'unité foncière concernée.

Tous ces choix pourraient être validés (ou invalidés) en une fois.

**Comment by alhyss** [comment]
_Le SG5 valide la dernière proposition._
