### ISSUE TITLE
Problème des doubles lignes en sld

### ISSUE THREAD

**Issue by JenniferIGN** [cnigfr/DDU-SG5-SYMBOLISATION#31]
Je retranscris ici les échanges par mail sur le sujet :

GPU : Symboles qui ne fonctionnent pas : 40-50 =balise ouvrante (remplacé par une image donc ok), 
07-65/66 et 43-50/51=décalages des hachures (c'est le problème des doubles lignes, le même que pour la presc 02 pour les PLU) ->  nouvelle proposition du CNIG là-dessus ?

_Leslie : Qu'est-ce qui posait problème avec le 40-50 ?_
GPU : la balise ouvrante étant un caractère spécial dans le SLD, nous ne sommes pas parvenus à l’utiliser comme un symbole (pour créer le sifflet du point de vue avec la parenthèse). Nous avons donc utiliser une image plus simplement.

_Leslie : Pour les 43-50 et 43-51, qui me paraissent tout de même beaucoup moins sophistiqués que la prescription 02, est-ce qu'il n'aurait pas été possible d'utiliser un motif qui superpose un trait vert de largeur 3 et un trait blanc de largeur 1.5 ?_
GPU : Si bien sûr, on peut faire ça et le rendu pour ce symbole sera similaire. Simplement, le fond entre les deux lignes de couleur sera masqué par le trait blanc et non transparent comme ce qui était prévu dans la charte. Nous allons partir là-dessus dans un premier temps côté GPU, avec des valeurs : 1.5 (blanc) et 3.5 (couleur) pour assurer une bonne lisibilité.

**Comment by GT-CNIG-DDU** [comment]
Pour le 40-50 Point de vue, nous sommes en attente de réponse du Ministère de la Culture sur la nature de ce symbole (ponctuel orienté ou pas, bi-linéaire, nécessité ou pas de l'arc de cercle...)
