### ISSUE TITLE
Création de symboles pour les codes INFO 40-01 et 40-02

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#38]
Codes INFO 40-01 *Périmètre d'un bien inscrit au patrimoine mondial* et INFO 40-01 *Zone tampon d'un bien inscrit au patrimoine mondial*.

Ils étaient passés entre les mailles du filet, visiblement, et n'ont pas de symbole à ce jour.

**Comment by alhyss** [comment]
Je suggèrerais bien de recycler ici une proposition qui avait été écartée pour un autre symbole, même si nous ne devrions pas avoir besoin des symboles linéaires et ponctuels qui allaient avec.

![info_40](https://user-images.githubusercontent.com/55992003/130407581-cf569507-47b7-4a59-842f-324815977a0b.png)

Le motif me semble plutôt bien coller avec l'objet, et il est facile de créer une déclinaison moins dense pour le sous-code 40-02. J'ai mis des couleurs discrètes, parce qu'il me semble que les périmètres UNESCO sont souvent très larges et on aurait vite tendance à ne plus voir que ça.

Pour le 40-01 :
```
Motif de points
• distance horizontale : 10 pt
• distance verticale : 10 pt

    Symbole simple
    • couleur de remplissage (RVB) : transparent
    • couleur de trait (RVB) : 255,196,118
    • largeur de trait : 0.8 pt
    • nom du symbole : circle
    • style de trait : ligne continue
    • taille : 20 pt

Ligne simple
• couleur (RVB) : 255,196,118
• largeur de trait : 0.8 pt
• style de trait : ligne continue
```

Pour le 40-02 :
```
Motif de points
• distance horizontale : 20 pt
• distance verticale : 20 pt

    Symbole simple
    • couleur de remplissage (RVB) : transparent
    • couleur de trait (RVB) : 255,196,147
    • largeur de trait : 0.8 pt
    • nom du symbole : circle
    • style de trait : ligne continue
    • taille : 40 pt

Ligne simple
• couleur (RVB) : 255,196,147
• largeur de trait : 0.8 pt
• style de trait : ligne continue
```

**Comment by alhyss** [comment]
En multipliant les dimensions par 1.5 :
![40_01_02_grossi](https://user-images.githubusercontent.com/55992003/132307852-f9df051a-4976-4509-97f3-0bede8c945cd.png)

**Comment by nkulpinski** [comment]
parfait

**Comment by alhyss** [comment]
_Le SG5 du 2021.09.07 valide la proposition avec dimensions multipliées par 1.5._
