### ISSUE TITLE
Ajout des zonages au projet QGIS de visualisation

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#4]
En première approche, uniquement les symboles basés sur `TYPEZONE`, sans prise en compte de l'attribut optionnel `DESTDOMI`.

**Comment by cartgab** [comment]
Cette représentation sur le libellé TYPEZONE est actuellement inapplicable sur un plan de zonage.
Cette information est beaucoup trop généraliste. Les communes désirent différencier, par exemple, les zones en Ua et Ub qui pour pour TYPEZONE la valeur U et le libellé Ua et Ub.
Toutefois, le standard ne s'adressant pas aux plans de zonage mais aux applications web, cette remarque n'est peut-être sans intérêt.

**Comment by alhyss** [comment]
@cartgab On rejoint là encore la question du catalogue de symboles, me semble-t-il. La proposition que j'ai présentée au GT de septembre (cf. [support sur GoogleDrive](https://drive.google.com/file/d/1MLHgMqkRS6bWL-_atCGGFIJs0lFhPyuL/view)) prévoyait d'ajouter un champ pour le choix du symbole dans les tables des prescriptions et des informations, mais il semblerait que ce soit également pertinent pour le zonage, en fait. Merci pour ton retour, j'en prends bonne note.

Sinon, l'objet de ce ticket était beaucoup plus terre-à-terre. Il s'agissait juste de faire en sorte que les préconisations qu'on trouvait pour les zonages dans le fichier Excel soient reprises dans le projet QGIS.

**Comment by alhyss** [comment]
Une question : faut-il ou non implémenter des étiquettes avec les libellés des zones dans le QML, considérant que le [guide](https://drive.google.com/drive/folders/1YHCxmiWknRLXUREbOYq4CUpvqYGZaw2Z) en prévoit pour les échelles supérieures au 1:2500, mais que le SG5 n'a jamais défini de spécifications pour les étiquettes jusque-là ?

On parle ce genre d'étiquettes :
![zone_urba](https://user-images.githubusercontent.com/55992003/112030640-c1c1ce00-8b3a-11eb-95de-dedd10cd0988.png)

Ça rejoint la discussion que nous avions eue sur l'étiquetage à partir du champ `TXT` dans l'issue #2, si ce n'est qu'il est cette fois explicitement dit dans le guide qu'il faut des étiquettes.

Nous pourrions :
- soit ne pas en mettre et les utilisateurs se débrouillent jusqu'à ce qu'on ait avancé sur le sujet ;
- soit définir proprement des spécifications et les implémenter dans les QML (peut-être un peu prématuré vu tous les chantiers en cours) ;
- soit - en attendant d'avoir proprement défini des spécifications - mettre des étiquettes dans les QML sans les traduire en spécifications littérales. Il serait alors logique d'avoir dans le [récapitulatif des préconisations](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/SYMBOLISATION/PLU/preconisations.md) une phrase pour alerter sur le fait que les étiquettes n'ont pas encore fait l'objet de spécifications arrêtées.

**Comment by GT-CNIG-DDU** [comment]
@tous. Merci @alhyss pour cette symbolisation QML illustrative.
Privilégions effectivement la troisième option dans l'immédiat mais en visant rapidement deuxième (la spécification) puisque c'est notre objectif.
A ce sujet, il suffit peut-être de demander à Marie et Pascal s'ils ne disposent pas de ces spécifications puisqu'ils les avaient implémentées sous ArcGIS (Marie en tout cas).
J'envoie des invitations au Github à Marie, Pascal, Nadège Thareau aussi (PSMV Besançon).

**Comment by alhyss** [comment]
Fait avec des étiquettes comme ci-dessus et qui ne font pas l'objet de spécifications littérales à ce stade.

J'ouvre une autre issue pour la définition desdites spécifications littérales, histoire de ne pas tout mélanger.

**Comment by GT-CNIG-DDU** [comment]
@alhyss, ok pour moi. Pensons à relancer Marie si elle ne répond pas.
Entre temps j'ai eu une idée : la maquette ESRI sur Nice nous donne toutes les infos dont on peut extraire les spécifs, non ? (à condition d'identifier la police de caractère, etc.)
Autre suggestion : je crois que le GPU répète régulièrement l'étiquette dans une grande surface (non, je ne parle pas de Carrefour...) ou à grande échelle. Bref... @JenniferIGN pourra sans doute nous fournir ces éléments car cette "étiquetage en poncif" semble indispensable.
Je copie cela dans le nouvel issue
