### ISSUE TITLE
Ajout d'un contour au code 07-53

### ISSUE THREAD

**Issue by Laetitia-aga** [cnigfr/DDU-SG5-SYMBOLISATION#47]
Bonjour, 

Concernant le code 07-53 du PSMV "mur de soutènement, remparts, mur de clôture à protégés, conserver...", il serait judicieux d'ajouter un contour à la ligne qui a la même couleur que le bâti de type B. Cela pose des problèmes de lecture dans le cas contraire. exemple ci-après ou j'ai une protection de mur sur la partie nord de la cour et qui vient recouvrir 2 bâtiments de type B

![image](https://user-images.githubusercontent.com/80510168/130919476-e4be5a13-240b-467d-adc1-0f847de891f2.png)

**Comment by GT-CNIG-DDU** [comment]
Bonjour Laetitia, Effectivement on ne distingue par le mur de soutènement... Pourrais-tu nous faire une (ou des) proposition de symbolisation intégrée dans le même extrait ? (le contour de la ligne doit-il être blanc, ou bien coloré pour le différencier à la fois du bâti et du fond d'écran ?)

**Comment by Laetitia-aga** [comment]
Je peux essayé de vous faire un extrait mais je ne sais pas coder comme Leslie (malheureusement) du coup ça sera un exemple uniquement visuel car en plus je ne travaille toujours pas en point mais en unité de carte. 

Cette histoire de contour est également à appliquer au symbole de code 07-50 / 07-52 / 07-67 qui correspond au classement des bâtiments.

_(Je ne suis pas très disponible en ce moment car finalisation du PSMV de Strasbourg dans les 4 mois à venir)_

**Comment by alhyss** [comment]
Bonne remarque ! J'avais pensé à mettre un contour pour les codes [07-50](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#prescription-07-50) (gris foncé), [07-52](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#prescription-07-52) (noir) et [07-67](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#prescription-07-67) (gris foncé) dans la proposition en attente de validation sur la [branche beta](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/tree/beta), par contre je n'avais pas du tout envisagé le cas des superpositions 07-52/07-53.

Je vous propose d'ajouter sous la ligne grise une ligne noire un peu plus épaisse :
![psc_07_53_contour_noir](https://user-images.githubusercontent.com/55992003/130942592-825f32b4-b15f-42e7-a2f5-346d7941c127.png)

```
Ligne simple
• couleur (RVB) : 0,0,0
• largeur de trait : 4.6 pt
• style de trait : ligne continue

Ligne simple
• couleur (RVB) : 102,102,102
• largeur de trait : 3 pt
• style de trait : ligne continue
```

Quand le mur traverse un bâtiment (même si j'imagine qu'en pratique il sera plutôt en bordure), ça donne :
![07-52_07-53](https://user-images.githubusercontent.com/55992003/130944152-b903013a-e4dc-45a9-bc3f-7dc7d5622336.png)


PS. Je ne suis pas favorable à l'idée des lignes blanches. D'une part parce que ça se verrait trop pour quelque chose qui n'est pas vraiment prévu par la légende, mais surtout parce qu'à certaines échelles ça risquerait de se confondre avec les espaces vides entre les bâtiments (alors qu'avec une bordure noire ou grise on comprend tout de suite que le trait fait partie du symbole).

*EDIT : coquille - référence au code 07-67 et pas 07-62.*

**Comment by Laetitia-aga** [comment]
Bonne idée pour le contour noir. Quand tu écris : _" J'avais pensé à mettre un contour pour les codes 07-50 (gris foncé), 07-52 (noir) et 07-62 (gris foncé)"_, pour le 07-62 pas besoin d'un contour je pense car cela représente de l'eau et donc pas de superposition avec une même couleur ? Par contre il faut prévoir un contour pour 07-67 (contour gris foncé sur aplat gris clair)

**Comment by alhyss** [comment]
Non, pardon, c'était une coquille. Je voulais écrire 07-67 et j'ai écrit 07-62 à la place... Je vais éditer mon post pour que ce soit plus clair.

J'ai donc bien mis une bordure gris foncé sur le [07-67](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#prescription-07-67), et pas sur le [07-62](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/beta/PSMV/preconisations.md#prescription-07-62).

Comme toi, je ne crois pas qu'il puisse y avoir de problème de superposition avec le 07-62. L'autre raison pour laquelle je n'ai pas mis de contour sur celui-là est qu'il est évident dans la légende nationale qu'il n'y en a pas, alors que pour le 07-52 et le 07-67 il semble bel et bien y avoir une fine bordure, respectivement noire et gris foncé. Mieux valait donc ne pas en ajouter un si ce n'était pas absolument nécessaire.

**Comment by alhyss** [comment]
_Le SG5 du 2021.09.07 valide la proposition._
