### ISSUE TITLE
Modification du symbole linéaire des prescriptions 07 du standard PLU

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#5]
_Proposition de S. Gabalda, validée par le SG5 du 2021.03.11._

L'objectif est de pouvoir plus aisément distinguer le symbole des géométries linéaires de celui des géométries surfaciques lorsque ce dernier est utilisé pour de petites emprises.

Diminution de la taille des symboles (de 12/18pt à 10/16pt + ajustement du motif en conséquence) et augmentation de l'épaisseur de la ligne (de 0.5pt à 1pt).

Concerne les deux symboles associés à ce code (07-00 à 03 et 07-04 à 05).

Avant :
```
Ligne de symboles
• décalage le long de la ligne : 17 pt
• intervalle : 23 pt

    Symbole de police
    • caractère(s) : unicode 234
    • couleur de remplissage (RVB) : 255,255,255
    • famille de police : Wingdings 2
    • taille : 18 pt

    Symbole de police
    • caractère(s) : unicode 234
    • couleur de remplissage (RVB) : 115,0,0
    • famille de police : Wingdings 2
    • taille : 12 pt

Ligne simple
• couleur (RVB) : 115,0,0
• largeur de trait : 0.5 pt
• style de trait : ligne continue
```
![07_avant](https://user-images.githubusercontent.com/55992003/111668619-384a8d00-8816-11eb-9ce0-06daa7c24287.png)

Après :
```
Ligne de symboles
• décalage le long de la ligne : 13 pt
• intervalle : 18 pt

    Symbole de police
    • caractère(s) : unicode 234
    • couleur de remplissage (RVB) : 255,255,255
    • famille de police : Wingdings 2
    • taille : 16 pt

    Symbole de police
    • caractère(s) : unicode 234
    • couleur de remplissage (RVB) : 115,0,0
    • famille de police : Wingdings 2
    • taille : 10 pt

Ligne simple
• couleur (RVB) : 115,0,0
• largeur de trait : 1 pt
• style de trait : ligne continue
```
![07_apres](https://user-images.githubusercontent.com/55992003/111668739-587a4c00-8816-11eb-9ca5-686682cce9b3.png)

_EDIT 2021.03.18 : ajout des images._

**Comment by cartgab** [comment]
Pour moi, cette évolution a été adoptée le 11 mars.
Toutefois, comme pour l'information, je définirais une largeur 1.5 pour le symbole linéaire.

**Comment by alhyss** [comment]
@cartgab À ce stade, une largeur de 1.5pt sur une ligne qui comporte déjà des symboles ne me paraîtrait pas cohérente avec les épaisseurs de ligne des autres symboles. Mais cf. #11 pour la question plus générale de la taille des symboles dans les préconisations PLU (vs préconisations PSMV).
