### ISSUE TITLE
Info ponctuelle 38

### ISSUE THREAD

**Issue by Geoscope19** [cnigfr/DDU-SG5-SYMBOLISATION#54]
Bonjour à tous,
Je vois dans la symbologie que pour le code 38 des informations la représentation n'est que surfacique. Or les sites Basias sont représentés par un ponctuel dans la base Géorisque. Du coup, ne vaudrait-il pas la peine de créer un symbole ponctuel pour le standard ?
Une suggestion : même couleur que le symbole surfacique, plutôt rond car il y a des ronds dans le symbole surfacique (police 
Wingdings en 10 normal), mais complété avec une différence de forme pour ne pas confondre avec le symbole de l'info 99 (la tête de mort pour des potentielles pollutions le fait bien, mais pas sûre que cela fasse l'unanimité ;-) )

![Info 38 - ponctuel](https://user-images.githubusercontent.com/81222128/134347499-da1eca2f-85f3-4161-a85e-a64aa1a23471.png)

**Comment by GT-CNIG-DDU** [comment]
Perso j'aime bien l'idée de la ☠
Sinon, en dehors de la façon dont Géorisques représente les sites Basias, y a-t-il réellement des prescriptions ponctuelles 38 ? car avec Basias on est plutôt sur des "sites industriels et activités de services" et le [L125-6 du code de l'environnement](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000028811074/) parle plutôt de  "**secteurs** d'information sur les sols qui comprennent les terrains où la connaissance de la pollution des sols justifie..."
Donc est-ce que ce ne sont pas plutôt des surfaces à l'échelle du document d'urbanisme ?

**Comment by alhyss** [comment]
Je pense aussi que cette information ne peut être que surfacique.

Les sites BASIAS ne sont pas des SIS (seulement l'une des sources annexes servant à leur élaboration) et la [méthodologie de délimitation](http://infoterre.brgm.fr/rapports/RP-68961-FR.pdf#page=36) de ces derniers est claire sur le fait que ce sont bien des périmètres. Il y a d'ailleurs des critères de précision très strictes - si on n'est pas capable de délimiter finement, on n'établit pas de SIS.

Cf. aussi sur Géorisques : https://www.georisques.gouv.fr/articles-risques/secteurs-information-sols

**Comment by Geoscope19** [comment]
Disons que dans les départements où j'interviens, je ne pense pas avoir de réel SIS mais les DDT me demandent systématiquement de mettre les sites Basias en annexe ! Peut-être une exigence infondée de leur part (ce ne serait pas la première fois !) à défaut d'élaboration de SIS (y a quand même des sites avec des "stériles" de mines d'uranium, hum, hum...).
On peut donc clore l'issue ?

**Comment by alhyss** [comment]
Je pense qu'on peut clore. Si c'est le code 99-00 qui doit être utilisé pour ces informations, alors il existe déjà un symbole ponctuel. 

Ceci étant dit, s'il s'avère que les sites BASIAS se retrouvent souvent en annexe des PLU (bien qu'il n'y ait a priori aucune obligation réglementaire), ils pourraient être évoqués dans les réflexions courantes du GT DDU sur l'opportunité d'ajout de codes d'information supplémentaires pour des informations facultatives...

**Comment by Geoscope19** [comment]
Bonjour,

Oui.

A bientôt

Elise HENROT
Gérante

*GEOSCOPE*
Tel. : 09 60 47 51 16
http://www.geoscope.fr <http://www.geoscope.fr/>

Je suis sociétaire de la coopérative ouvaton.coop 
<https://ouvaton.coop/la-cooperative/nos-valeurs/>: les mails sont 
stockés sur des serveurs localisés en région parisienne et l'hébergeur 
garantit une protection de leur contenu par des règles strictes de 
confidentialité.

Le 04/10/2021 à 13:48, alhyss a écrit :
