### ISSUE TITLE
Transparence des fond unis

### ISSUE THREAD

**Issue by nkulpinski** [cnigfr/DDU-SG5-SYMBOLISATION#56]
Ne serait-il pas utile de proposer par défaut une transparence de 30% sur chaque surfacique de couleur pleine ?

**Comment by alhyss** [comment]
*Le SG5 du 16 novembre 2021 acte la suppression de la transparence de couche sur les informations surfaciques. La transparence est désormais gérée symbole par symbole.*

PSC 45 : transparence du fond à 40%.
INFO 02 : transparence du fond à 60%.
INFO 16 : transparence du fond à 40%.
INFO 31 : transparence du fond à 40%.

Pas de transparence pour l'INFO 98 - caviardage effectif des périmètres d'annulation partielle.
Pas de transparence pour l'heure sur les prescriptions PSMV 03-51, 07-50, 07-52, 07-62, 07-67.

**Comment by alhyss** [comment]
Si ça convient à tout le monde, je vais aussi mettre une transparence de 40% sur tous les aplats des INFO droit de préemption, tant que nous n'aurons pas décidé des symboles qui les remplaceront.

Nous n'en avons pas parlé, au final, mais je pense aussi laisser la transparence de 40% sur les lignes de l'INFO 30. Il me semble que les projets urbains partenariaux peuvent couvrir des périmètres assez étendus et qu'il n'y a pas lieu de masquer complètement le fond de plan dans ce cas.

Autre point, je me suis rendu compte que l'INFO 98 (les périmètres d'annulation partielle) était jusque-là dessinée sur la première couche de rendu, comme tous les aplats. Si nous voulons qu'elle recouvre toutes les prescriptions qui ne s'appliquent pas, elle devrait au contraire passer sur la dernière couche. Je modifie le QML en ce sens.
