### ISSUE TITLE
Bibliothèque de styles ArcGIS pro

### ISSUE THREAD

**Issue by nkulpinski** [cnigfr/DDU-SG5-SYMBOLISATION#57]
#55 
La nouvelle organisation de l'archive de symbolisation est à valider avec ses nouveaux éléments comprenant les fichiers stylx et les projets ArcGIS pro.
Les planches de contacts se trouvent dans les dossiers planches de PLU et de PSMV

**Comment by GT-CNIG-DDU** [comment]
Vu. Mais n'avait-on pas conclu au GT DDU que l'on ne conservait qu'une seule version des planches contacts, à titre d'illustration des spécifications ?

**Comment by nkulpinski** [comment]
Oui en effet mais ça permet à tous de pouvoir contrôler
A terme les planches de contacts arcgispro disparaitrons et ne seront pas poussées

**Comment by alhyss** [comment]
Il y a une certaine différence de rendu sur le code INFO 20. Les croix paraissent beaucoup plus petites et épaisses avec les styles ArcGIS.

**Comment by alhyss** [comment]
*Le SG5 du 16 novembre 2021 valide la publication des symboles ArciGIS Pro (sans la planche de contact), après ajustement du symbole INFO 20.*

**Comment by nkulpinski** [comment]
validé et ajouté à la branche principale
