### ISSUE TITLE
codes hexadecimaux pour les couleurs

### ISSUE THREAD

**Issue by nkulpinski** [cnigfr/DDU-SG5-SYMBOLISATION#59]
Je viens de pousser dans la branche beta #58 le fichier preconisation.md complété des codes (HEX) sur 6 caractères pour les codes couleurs RVB
Je vais en faire de même pour les préconisations PSMV

**Comment by alhyss** [comment]
Salut Nicolas,

Je ne conteste vraiment pas l'utilité, et merci d'avoir fait le boulot (pas à la main, j'espère ?), mais ça va avoir une durée de vie très limitée si ce n'est pas intégré à mes scripts... Les fichiers des préconisations sont déduits des QML, donc intégralement recalculés à chaque fois que ces derniers sont modifiés.

Ce n'est peut-être pas la peine que tu t'embêtes à refaire le travail pour les PSMV dans ces conditions.

J'ai bien noté qu'il faudra que je rajoute ça aux scripts, en tout cas.

*EDIT : si la conversion RVB/hexadécimale peut être gérée proprement sous PostgreSQL, ce sera ajouté dans la fonction `qml_retro_traduction_qml` du script [retro_traduction_qml.sql](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/SYMBOLISATION/__outils__/retro_traduction_qml.sql#L355). Sinon je ferai ça en python, avec un retraitement a posteriori du résultat des fonctions de [recapitulatif_markdown.sql](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/SYMBOLISATION/__outils__/recapitulatif_markdown.sql). Il n'y a pas de difficulté particulière quoi qu'il en soit.*

**Comment by nkulpinski** [comment]
Si à la main …

Ok je te laisse faire pour la prochaine modif

A+

**Comment by alhyss** [comment]
Oh... Désolée alors, on aurait dû en discuter plus tôt.

**Comment by alhyss** [comment]
Les scripts ont déjà été modifiés pour ajouter automatiquement les codes hexadécimaux (en instance de publication).

*Le SG5 du 16 novembre 2021 valide l'ajout des codes hexadécimaux et acte par ailleurs que la transparence doit apparaître de la manière suivante dans les préconisations :*

```
• couleur de remplissage (RVB) : 86,170,2 (#56aa02), transparence 40%
```

Elles étaient jusqu'à présent représentées par des coordonnées RVBA.
