### ISSUE TITLE
Création d'un symbole pour la prescription 97-00 et l'information 97-00 du standard PLU

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#7]
Prescription "_Périmètre d'application d'une pièce écrite territorialisée (rapport de présentation, PADD, règlement, règlement graphique, POA)_" et information "_Périmètre d'application d'une pièce écrite territorialisée relative aux annexes (liste des annexes, liste des SUP, plan des SUP)_", introduites par la version 2017c du standard PLU, dans le cadre de la prise en charge des pièces écrites territorialisées.

**Comment by alhyss** [comment]
_Décision du SG5 du 2021.03.11._ 

Symbole invisible :
```
Remplissage simple
• style de remplissage : pas de remplissage
• style de trait : pas de ligne
```

**Comment by cartgab** [comment]
Il me semble que cette symbolisation a été validée le 11 mars.
De plus, je la trouve pertinente étant donnée que la visualisation du champ d'application d'une pièce écrite territoriale ne se justifie pas forcément.
Mais faut-il dans cette information indiquer le SCOT, PDU, SD assainissement,..... Dans un tel cas, faut-il indiquer en valeur : Schéma de cohérence territoriale (SCoT), plan de déplacement urbain (PDU), schéma directeur assainissement (SDA),....

**Comment by GT-CNIG-DDU** [comment]
@cartgab : cette question ne concerne pas la symbolisation mais le standard CNIG PLU.
Les pièces écrites territorialisées y sont traitées page 45/63 (et les plans de secteur page 51).

**Comment by cartgab** [comment]
J'ai compris la remarque... les noms indiqués étaient pour discuter... la question était terre à terre.
Comment faire pour appliquer la normalisation qui prévoit 4 documents pour le SCOT ? Faut-il créer un document unique SCOT qui regroupe les 4 documents ?
Toutefois je n'ai toujours pas compris son application ? Est-ce que ce périmètre s'applique pour un PDU, PLH, SDA.... ?

**Comment by alhyss** [comment]
@cartgab Si tu t'interroges, l'issue a été fermée automatiquement quand j'ai appliqué la modification qu'elle visait, à savoir l'implémentation du symbole de la prescription 97-00 et l'information 97-00. Même si je ne suis pas sûre que ce soit le meilleur lieu pour discuter de la mise en oeuvre du standard, ça ne devrait pas vous empêcher de poursuivre la discussion.

Merci quoi qu'il en soit de ne pas rouvrir l'issue, sinon je n'arriverai jamais à m'y retrouver.
