### ISSUE TITLE
Catalogue de symboles - format et contenu

### ISSUE THREAD

**Issue by mariondumont** [cnigfr/DDU-SG5-SYMBOLISATION#71]
**Format**
TODO

**Contenu**
Pour chaque symbole, seront nécessaires (à compléter) : 
- son code
- l'intitulé de légende correspondant (phrase courte)
- une description plus détaillée des objets visés (références métier, quels usages/besoins, etc)
- représentation multiple en fonction de l'échelle ? oui/non : 
- pour chacune des représentations 
  * description de la représentation (comme dans les préconisations du Guide CNIG)
  * vignette
  * échelle min/max de visibilité (dénominateur)

**Comment by GT-CNIG-DDU** [comment]
Je clos cette issue à poursuivre ici #75

**Comment by GT-CNIG-DDU** [comment]
Je clos cette issue à poursuivre ici #75
