### ISSUE TITLE
Catalogue de symboles – nommage des symboles - Objets masqués

### ISSUE THREAD

**Issue by mariondumont** [cnigfr/DDU-SG5-SYMBOLISATION#72]
Pour permettre le non affichage de certains objets, et l’amélioration de la lisibilité globale (ex. DPU), un code INVISIBLE sera également référencé au catalogue dans les valeurs possibles pour SYMBOLE. Pour ce code, le GPU ne représentera l’objet de manière invisible pour qu’il sorte quand même dans le résultat des requêtes utilisateurs.

**Comment by alhyss** [comment]
*Ce point a fait l'objet d'un vote au cours du SG5 du 9 juin 2022 : 3 voix pour l'usage de codes `<couche>-<S/L/P>_<typepsc>-<stypepsc>_000` (cf. [propositions de spécifications](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/issues/68#issuecomment-1137004274) dans l'issue #68), 3 voix pour l'usage d'un code unique `INVISIBLE`, 1 abstention. Le pilote du GT DDU tranche pour la première option au motif de la cohérence interne des standards.*
