### ISSUE TITLE
Prototype de Registre des symboles

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [cnigfr/DDU-SG5-SYMBOLISATION#75]
J'ai fait un prototype de registre des symboles sous Airtable avec  :
- une vue Tableur
- une vue Formulaire du demandeur
- une vue Catalogue de symboles

Le liens de partage avec droits en édition est [celui-ci](https://airtable.com/invite/l?inviteId=invLiS3wXN9E6Z26O&inviteToken=f7293718c557f7960705b41ab9be0014233592a582374af4e8c8f8cc4228c3ff&utm_source=email)

A tester... modifier, **améliorer par le SG5** ! 

Le lien "[Open Form](https://airtable.com/shr0hh1KcxwffjdeW)" vous donne directement accès au formulaire

_PS : je découvre Airtable à cette occasion... [bon tuto ici](https://la-webeuse.com/tutoriel-airtable-planificateur-blog/#lwptoc26)_

**Comment by GT-CNIG-DDU** [comment]
Ajout des champs Echelle_Min et Echelle_Max au prototype de registre.

**Comment by GT-CNIG-DDU** [comment]
Intégration de la classe d'objet ZONE_URBA dans le registre afin de pouvoir affecter des symbolisations alternatives en fonction du `LIBELLE` de zone
Intégration de la table PrescriptionUrbaType du standard PLU avec le code-sous-code (CSC) comme clé de saisie.
Todo1 : Faire de même pour InfomationUrbaType...
Todo2 : Je n'ai pas encore trouvé pourquoi le formulaire ne propose pas CSC + Libellé...

**Comment by GT-CNIG-DDU** [comment]
Intégration de la table InformationUrbaType du standard PLU avec le code-sous-code (CSC) comme clé de saisie.
Intégration d'un champ booléen "Le symbole varie-t-il en fonction de l'échelle" ? avec apparition des champs "échelle min" et "échelle max" dans le formulaire de saisie, dans ce cas.

**Comment by mariondumont** [comment]
Avis IGN : 
* registre : ok très bien pour nous
* formulaire : 
** peut-être judicieux de forcer une demande unique par type d'objet (càd si on veut faire une demande pour un zonage et une presc, il faut faire deux demandes)
** question : comment pourrait être gérée la modération des demandes avec cet outil ? est-ce le champ date de validation CNIG qui permet de distinguer la partie validée du registre ?

**Comment by GT-CNIG-DDU** [comment]
_peut-être judicieux de forcer une demande unique par type d'objet (càd si on veut faire une demande pour un zonage et une presc, il faut faire deux demandes)_
Bien vu Marion. Le champ "`classe d'objet`" était de type "Multiple select" ce qui était une erreur, le voici désormais "Single select"

_est-ce le champ de type date `Validation CNIG` qui permet de distinguer la partie validée du registre ?_
C'est l'idée oui.

**Comment by alhyss** [comment]
*Le prototype a fait l'objet d'une présentation au cours du SG5 du 9 juin 2022. Il est acté de poursuivre ces travaux exploratoires, en examinant notamment les aspects suivants :*
- *processus organisationnel pour l'instruction des demandes d'ajout de symboles au registre (première trame par @nkulpinski et @Estellealleman) ;*
- *test du formulaire sur des cas concrets ;*
- *examen des possibilités de synchronisation automatique des données entre le Git et le registre (@alhyss) ;*
- *recherche d'alternatives libres à Airtable ([Démarche simplifiées](https://www.demarches-simplifiees.fr/) ?).*

**Comment by nkulpinski** [comment]
Suite à la décision de poursuivre ces travaux directement sur GitHub et notamment avec les formulaire de propose de clore cette issue

**Comment by GT-CNIG-DDU** [comment]
Je suis d'accord pour clore cette issue.
