### ISSUE TITLE
Prototype démo Qgis catalogue de symbo

### ISSUE THREAD

**Issue by mariondumont** [cnigfr/DDU-SG5-SYMBOLISATION#76]
Vous trouverez ci-joint le prototype Qgis contenant les couches du GPU agrémentées du code SYMBOLE.
Les dernières règles de nommage ont été appliquées (excepté le passage du numéro sur 3 caractères, c'est noté)

**Comment by GT-CNIG-DDU** [comment]
Merci @mariondumont et à l'équipe de développement IGN.
Pour le moment le prototype n'affiche pas les prescriptions / informations (à grande échelle).

Depuis mon appel vendredi j'en ai trouvé la raison Marion : 
Les données sont codées `PSC-S_05_0001` pour le champ symbole (ce qui est conforme modulo le 0001 au lieu de 001)
mais la règle d'affichage de la symbologie de la couche est inexacte: `symbole = 'PSC_05_S_0001'` (mauvais emplacement du S)

**Comment by mariondumont** [comment]
Démonstrateur corrigé (coquille dans la symbo des infos/presc)
La note sur les 4 chiffres reste valable !

[POC_catalogue_symbo.zip](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/files/8754958/POC_catalogue_symbo.zip)

**Comment by GT-CNIG-DDU** [comment]
Merci pour la correction !
Voici quelques suggestions d'amélioration : 
- le typepsc 99 entraîne un SYMBOLE = `PSC-S_OTHER_0001` (au  lieu de `PSC-S_99_0001`, idem pour P et L)
- il y a des règles de symbologie marquées : `symbole = 'PSC-S_07-65_ET_43-50_0001'` (?)

Pour les besoins du prototype, il serait intéressant de remplir quelques stypepsc (actuellement tous `NULL`),
et de symboliser les ZONES conformément [aux spécifs](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/SYMBOLISATION/PLU/planches/plu_zone_sup2500_planche_1.png) au delà de l'échelle 17060.

**Comment by Geoscope19** [comment]
Bonjour,

Cela ne concerne pas les symboles, mais petit détail pour zone Urba : Nom des zones de la couche "zone_urba" : forcer l'étiquette dans le polygone (cf. [capture d'écran](https://geoscope.fr/nextcloud/index.php/s/9Hajq6dC6R5HQqS))

**Comment by GT-CNIG-DDU** [comment]
Pour info @Geoscope19, tu peux tout à fait copier puis coller une (petite !) image dans un commentaire d'issue.

**Comment by GT-CNIG-DDU** [comment]
Comme ça : 

![image](https://user-images.githubusercontent.com/79853274/223724969-1910d777-df63-4cce-967a-7d3cf337c30e.png)

**Comment by GT-CNIG-DDU** [comment]
et sur le fond : entièrement d'accord  ;-)

**Comment by nkulpinski** [comment]
SI toujours nécessaire
Mettre à jour le prototype QGIS avec les dernières décisions du SG5
La nomenclature actuelle de la base de données ne correspond pas à la nomenclature actuelle du champ symbole par exemple :)

**Comment by GT-CNIG-DDU** [comment]
Plus que nécessaire pour tous les utilisateurs de QGIS.
Mais qui peut prendre cette action après le départ de @mariondumont ?

**Comment by nkulpinski** [comment]
J'ai assigné à @JenniferIGN en attendant
