### ISSUE TITLE
visualisateur devient visualiseur

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [cnigfr/DDU-SG5-SYMBOLISATION#8]
Je propose de remplace "visualisateur" par "visualiseur", partout

**Comment by alhyss** [comment]
En fait, j'ai bien l'impression qu'aucun de ces deux mots n'existe (certains correcteurs orthographiques ont l'air plus tolérants avec "_visualiseur_", mais les dictionnaires n'ont pas l'air de le connaître non plus).

Quitte à inventer un mot, "_visualisateur_" avait l'intérêt d'être dans la veine de présenter-présentation-présentateur, démontrer-démonstration-démonstrateur, valider-validation-validateur etc. Mais ce n'est pas satisfaisant quoi qu'il en soit.

Je me demande s'il ne vaudrait pas mieux en rester à "_projet QGIS de visualisation des préconisations_", évidemment raccourci dès que le contexte permet d'en enlever une partie.

**Comment by cartgab** [comment]
Le projet permettant de visualiser les spécifications et préconisations en termes de symbolisation, je mettrais l'accent sur la symbolisation.
De plus, je mettrais en cohérence avec la documentation actuelle sur le sujet se nommant "date_documentation_symbolisation".
Leslie m'avait proposé "cnig_plu_symbologie_qgis_3_10" mais pourquoi pas "date_qgis310_symbolisation_plu" ?

**Comment by alhyss** [comment]
@cartgab Mettre la date me complique la vie, à vrai dire, car ça veut dire que le nom du fichier n'est pas stable. Je n'ai pas envie de devoir penser à corriger les URL dans tous les *readme.md* et autres fichiers de documentation où j'aurais fait référence au projet QGIS à chaque mise à jour.

Pour info, dans la version que je viens de publier, l'archive s'appelle *[projet_qgis_symbolisation_plu.zip](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/blob/SYMBOLISATION/PLU/projet_qgis_symbolisation_plu.zip)* et le projet qu'elle contient *qgis310_symbolisation_plu.qgz*.

Je ne pense pas non plus qu'il faille se prendre la tête avec ce genre de chose. Les utilisateurs peuvent changer le nom si ça leur chante. Dans cette optique, j'enlève le label "à valider SG5" que tu as mis. Si on commence à attendre une validation du sous-groupe sur des détails qui ne concernent pas le fond des préconisations, on ne s'en sortira jamais. Sauf si tu vois un enjeu qui m'échappe, je préfère m'en tenir à ce que j'ai mis. C'est court comme tu le souhaitais et c'est pratique pour moi.

@GT-CNIG-DDU Pour ce qui est de *visualisateur*/*visualiseur*, j'ai dû corriger partout sauf dans mes scripts, où j'utilise toujours *visualisateur*, y compris dans les noms des fichiers *visualisateur_qgis_creation_grille_data.sql* et *visualisateur_qgis_creation_grille.sql*. Est-ce que c'est tolérable comme ça ou faut-il éradiquer complètement le terme ?

**Comment by GT-CNIG-DDU** [comment]
+1 pour l'absence de date dans le nom du fichier, comme dit précédemment on réservera la mention de la date à la publication de versions identifiées.
Ok pour le nom du fichier et la suppression du label "à valider SG5".

@alhyss  Merci pour la correction "visualiseur". Pour te répondre ce ne serait pas très cohérent de conserver les deux termes. Donc : reste plutôt à "visualisateur" partout si le coup est parti et que c'est trop compliqué à modifier, ou bien "visualiseur" partout si c'est encore possible sans que cela occasionne une charge et un risque trop importants.

**Comment by alhyss** [comment]
@GT-CNIG-DDU Désolée, je n'étais pas claire. En fait je n'ai mis *visualiseur* nulle part à ce stade. Par "corrigé partout sauf dans mes scripts" je voulais juste dire que le terme *visualisateur* n'apparaît plus. J'ai mis d'autres expressions à la place, comme "projet de visualisation". L'ex-répertoire "visualisateur" est devenu "maintenance", etc.

Il n'y aurait pas particulièrement de risque à changer dans les scripts et ce ne serait pas long à faire (ce n'est jamais qu'un rechercher/remplacer). J'ai juste oublié de le faire en même temps que mes modifications pour l'ajout des zones. Tu préfères que je change aussi, donc ?

**Comment by GT-CNIG-DDU** [comment]
Oui. Je préfère visualiseur (et même visualisateur) à des paraphrases. "Maintenance" n'est pas très parlant.
Donc oui je préfère que tu changes, mais ce n'est pas prioritaire et fais-le uniquement à la condition que cela ne t'impose pas une charge supplémentaire trop importante.

**Comment by alhyss** [comment]
@GT-CNIG-DDU Oh, je n'ai pas changé le nom du [répertoire](https://github.com/GT-CNIG-DDU-team/SG5-SYMBOLISATION/tree/SYMBOLISATION/PLU/maintenance) à cause de ça mais parce que *visualisateur*/*visualiseur* laissait entendre qu'il contenait les outils de visualisation alors qu'on n'y trouve que les scripts qui, de fait, servent à la maintenance desdits outils de visualisation. Ça me paraissait au contraire beaucoup plus clair. Ce n'est pas le cas ?

Je vais changer dans les scripts.

**Comment by GT-CNIG-DDU** [comment]
@alhyss "Maintenance" ne me parle pas.
Peut-on le renommer en "Scripts" ? En gardant le readme : "(Scripts de) maintenance des outils"
