### ISSUE TITLE
Prescription 05 Linéaire et Ponctuel ?

### ISSUE THREAD

**Issue by nkulpinski** [cnigfr/DDU-SG5-SYMBOLISATION#81]
Bonjour à tous,
je me pose la question de savoir si il existe vraiment des documents avec les emplacement réservés représentés avec des linéaires ou des ponctuels ?
Est-il possible de vérifier dans la base du GPU si cette utilisation est faite ? SI le résultat est nul, ne pourrions nous pas retirer ces représentations pour les codes 05_xx ?

**Comment by alhyss** [comment]
@nkulpinski Pour bien comprendre, en quoi est-ce que tu penses que ça nous aiderait de supprimer ces symboles ?

**Comment by nkulpinski** [comment]
@alhyss je me suis posé la question parce que je ne les utilise pas et je ne voyais pas d'utilisation de ces symboles mais une collègue utilise les linéaires, donc maintenant je vois 😅 
C'etait un questionnement mais l'issue ne fera pas long feu 😄

**Comment by nkulpinski** [comment]
On ne change rien et on conserve les linéaires et ponctuels
