### ISSUE TITLE
Ajout d'un symbole linéaire pour l'information 16-00 du standard PLU

### ISSUE THREAD

**Issue by alhyss** [cnigfr/DDU-SG5-SYMBOLISATION#9]
_Suggestion de S. Gabalda._

Information 16-00  "_Site archéologique_".

L'objectif est de permettre la représentation de voies antiques, anciennes murailles et autres objets susceptibles d'être modélisés par des géométries linéaires.

**Comment by alhyss** [comment]
_Proposition de symbole faite par S. Gabalda._

![info_16_00_proposition_1](https://user-images.githubusercontent.com/55992003/110914579-d91ce200-8316-11eb-85f5-551d9ad69d68.png)

```
Ligne de symboles
• décalage de la ligne : -1 pt
• décalage le long de la ligne : 14 pt
• intervalle : 20 pt

    Symbole de police
    • caractère(s) : unicode 171
    • couleur de remplissage (RVB) : 255,255,255
    • couleur de trait (RVB) : 215,176,158
    • famille de police : Wingdings
    • largeur de trait : 1 pt
    • taille : 12 pt

Ligne simple
• couleur (RVB) : 215,176,158
• largeur de trait : 2 pt
• style de trait : ligne continue
```

NB : je me suis permis de faire porter le décalage d'1pt sur les symboles plutôt que sur la ligne pour que cette dernière reste calée sur la géométrie. Le décalage le long de la ligne (= espace entre les symboles + 1/2 taille du symbole) est un ajout que j'ai fait systématiquement sur les lignes de symboles, car il ne me semble pas très heureux de commencer sur un symbole.

**Comment by alhyss** [comment]
Je trouve un peu dommage de ne pas réutiliser le symbole d'étoile qui sert aux ponctuels, qui a l'avantage d'être différent de celui des prescriptions 07.

Ma proposition : 

![info_16_00_proposition_2](https://user-images.githubusercontent.com/55992003/110915354-cf47ae80-8317-11eb-9020-ec6eb9681a6f.png)
```

Ligne de symboles
• décalage le long de la ligne : 11 pt
• intervalle : 16 pt

    Symbole de police
    • caractère(s) : unicode 181
    • couleur de remplissage (RVB) : 215,176,158
    • famille de police : Wingdings
    • taille : 10 pt

Ligne simple
• couleur (RVB) : 215,176,158
• largeur de trait : 1 pt
• modèle de tiret personnalisé (tiret ; espace) : 6;10 pt
```

**Comment by cartgab** [comment]
Je suis d'accord, j'ai oublié de modifié ce symbole après avoir une la solution pour ajouter un nouveau symbole (nouveau fichier de style) sur mon environnement et dans QGIS.
Simplement, je mettrais un trait de largeur 1.5. Je trouve que la différence entre 0.5 et 1 ne se voit pas bien à l’œil humaine. D'ailleurs j'appliquerais également cela pour tous les autres symboles dont pour les prescriptions 07-00 et 07-06

**Comment by alhyss** [comment]
Bonjour @cartgab.
Juste pour que je comprenne : quel est exactement l'enjeu ici dans le fait de pouvoir distinguer le trait d'épaisseur 1pt du symbole linéaire d'un trait d'épaisseur 0.5pt ? C'est l'un des rares codes dont le symbole surfacique n'a pas un contour à 0.5pt (et il a aussi un aspect radicalement différent du linéaire).

**Comment by cartgab** [comment]
Comme indiqué, c’est pour le voir visuellement sur un plan de zonage.
Un alignement est parfois mis sur une limite de zonage, c’est le cas d’un mur qui est identifié en plus du bâtiment ou encore un alignement qui est en limite de zonage.
Et un trait fin est parfois peu visible selon la couleur, c’est notamment le cas pour la voie antique (information 16-00)
Si cela pose un problème, ne change rien. Je n’appliquerai pas les préconisations. C’est tout.

Edit : suppression informations personnelles.

**Comment by alhyss** [comment]
@cartgab Foncièrement, ça ne me pose pas de problème. Je m'interroge aussi sur l'épaisseur des traits - 0.5pt me semble vraiment très léger (et même trop léger pour QGIS quand il s'agit de tirets), y compris pour une visualisation à l'écran. Il ne me paraîtrait pas absurde d'envisager de passer les épaisseurs 0.5pt à 0.8pt et, par suite, peut-être les 1pt à 1.5pt, les 1.5pt à 2pt, les 2pt à 2.5pt... Mais je pense que ça doit être fait de manière cohérente sur tous les symboles (il y a une logique dans les épaisseurs de trait qu'il me semble judicieux de préserver), sur la base d'un comparatif avant/après, et sans perdre de vue qu'une telle évolution impacterait presque tous les symboles. À mettre à l'ordre du jour du prochain SG5 ?

Tant que le SG5 n'aura pas décidé de revoir les épaisseurs, je trouve préférable de garder ici l'épaisseur de 1pt utilisée pour tous les motifs composés symbole/tiret.

**Comment by alhyss** [comment]
_Le SG5 valide le symbole linéaire reprenant le poncif du symbole ponctuel, avec une épaisseur de trait à 1.5pt._
