### ISSUE TITLE
Demande de symbolisation pour les codes PSC-S_18-12, PSC-S_18-13 et PSC-S_18-14

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [cnigfr/DDU-SG5-SYMBOLISATION#93]
Demande de symbolisation pour les codes PSC-S_18-[12,13 et 14] intégrés dans le projet de révision du standard PLU/CC v2022-10

-- | -- | -- | -- |  --  |
|--|--|--|--|--|
18|12| OAP secteurs de renaturation | [L. 151-7 I 4°](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043977769) |  --  |
18|13| OAP relatives à la protection des franges urbaines et rurales | [L.151-7 I 7°](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043977769) |  --  |
18|14| OAP recul du trait de côte | [L.151-7 III](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043977769) |  --  |

**Comment by nkulpinski** [comment]
A l’heure actuelle tous les codes PSC-S_18-xx_001 portent le symbole par défaut du PSC-S_18-00_001
Est-il nécessaire d'attribuer une symbolisation pour ces trois sous-codes ? Sinon il serait plus judicieux d'attribuer une symbolisation pour chacun des sous-codes 18 ... ?

**Comment by nkulpinski** [comment]
Il en est de même pour les issues #89  et #90

**Comment by nkulpinski** [comment]
Symbole général conservé
